### ISSUE TITLE
production version went error

### ISSUE THREAD

**Issue by php-cpm** [pantsel/konga#100]
I cloned code from github master branch
after i run `npm run production`
log comes 
```

> node --harmony app.js --prod

Hook:api_health_checks:process() called
Hook:health_checks:process() called
Hook:user_events_hook:process() called
User had models, so no seed needed
Kongnode had models, so no seed needed
Emailtransport had models, so no seed needed
Error: The hook `grunt` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.grunt._hookTimeout to a higher value (currently 60000)
    at Timeout.tooLong [as _onTimeout] (/data0/somepath/konga/20170920-162052/node_modules/sails/lib/app/private/loadHooks.js:85:21)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by pantsel** [comment]
Hi @php-cpm ,
check out [this issue on Sails.js repo](https://github.com/balderdashy/sails/issues/2691).

You can increase hook timeouts by modifying <code>hookTimeout</code> attribute in <code>config/env/production</code>. Try giving it a higher value and run the app again.

**Comment by php-cpm** [comment]
i checked that config，AND  i guess `hookTimeout: 60000` must be a large number

**Comment by pantsel** [comment]
Get it higher
