### ISSUE TITLE
ReferenceError: _ is not defined     at patch (/konga/node_modules/sails-hook-validation/index.js:34:10)

### ISSUE THREAD

**Issue by dragon28** [pantsel/konga#104]
Hello People,

Sorry to disturb you guys but found  an new issue:

$ npm start

> kongadmin@0.8.4 start /home/dragon/konga
> node --harmony app.js

debug: Hook:api_health_checks:process() called
debug: Hook:health_checks:process() called
debug: Hook:user_events_hook:process() called
/home/dragon/konga/node_modules/sails-hook-validation/index.js:34
        (_ || sails.util._)
         ^

ReferenceError: _ is not defined
    at patch (/home/dragon/konga/node_modules/sails-hook-validation/index.js:34:10)
    at /home/dragon/konga/node_modules/sails-hook-validation/index.js:101:21
    at /home/dragon/konga/node_modules/sails/lib/app/private/after.js:91:14
    at /home/dragon/konga/node_modules/async/lib/async.js:721:13
    at /home/dragon/konga/node_modules/async/lib/async.js:52:16
    at done (/home/dragon/konga/node_modules/async/lib/async.js:246:17)
    at /home/dragon/konga/node_modules/async/lib/async.js:44:16
    at Sails.<anonymous> (/home/dragon/konga/node_modules/async/lib/async.js:718:17)
    at Sails.<anonymous> (/home/dragon/konga/node_modules/async/lib/async.js:167:37)
    at Sails.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Sails.emit (events.js:185:7)
    at Sails.emitter.emit (/home/dragon/konga/node_modules/sails/lib/app/private/after.js:50:11)
    at /home/dragon/konga/node_modules/sails/lib/app/private/loadHooks.js:103:15
    at /home/dragon/konga/node_modules/sails-hook-orm/node_modules/async/lib/async.js:52:16
    at /home/dragon/konga/node_modules/sails-hook-orm/node_modules/async/lib/async.js:550:17
    at /home/dragon/konga/node_modules/sails-hook-orm/node_modules/async/lib/async.js:544:17
    at _arrayEach (/home/dragon/konga/node_modules/sails-hook-orm/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/home/dragon/konga/node_modules/sails-hook-orm/node_modules/async/lib/async.js:543:13)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

npm ERR! Linux 4.10.0-35-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! kongadmin@0.8.4 start: `node --harmony app.js`
npm ERR! Exit status 1

Please do take a look at the mentioned issue.

Thanks

**Comment by pantsel** [comment]
Have you tried running npm install manually?

**Comment by dragon28** [comment]
@pantsel  

I deleted the node_modules directory and run npm install which produce the same error message...

I also tried manually run npm install and again it produce the same error message....

I would like to make a suggestion that you try to make a vagrant environment just like kong-vagrant 

https://github.com/Mashape/kong-vagrant

Thanks

**Comment by mingfang** [comment]
i'm seeing the same error

**Comment by pantsel** [comment]
@dragon28  ,
It turned out to be an external dependency issue. It is fixed with the latest commits.
