### ISSUE TITLE
Release 0.8.5 does not start in docker

### ISSUE THREAD

**Issue by marckhouzam** [pantsel/konga#108]
I've only tried in docker, but both on Windows and Linux and pantsel/konga:0.8.5 fails to start with the following error:

> docker run --rm --name konga -p 1337:1337 pantsel/konga:0.8.5
debug: Hook:api_health_checks:process() called
debug: Hook:health_checks:process() called
debug: Hook:user_events_hook:process() called
/app/node_modules/sails-hook-validation/index.js:34
        (_ || sails.util._)
         ^

ReferenceError: _ is not defined
    at patch (/app/node_modules/sails-hook-validation/index.js:34:10)
    at /app/node_modules/sails-hook-validation/index.js:101:21
    at /app/node_modules/sails/lib/app/private/after.js:91:14
    at /app/node_modules/async/lib/async.js:721:13
    at /app/node_modules/async/lib/async.js:52:16
    at done (/app/node_modules/async/lib/async.js:246:17)
    at /app/node_modules/async/lib/async.js:44:16
    at Sails.<anonymous> (/app/node_modules/async/lib/async.js:718:17)
    at Sails.<anonymous> (/app/node_modules/async/lib/async.js:167:37)
    at Sails.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Sails.emit (events.js:185:7)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:50:11)
    at /app/node_modules/sails/lib/app/private/loadHooks.js:103:15
    at /app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:52:16
    at /app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:550:17
    at /app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:544:17
    at _arrayEach (/app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:543:13)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by mubeennakade** [comment]
@marckhouzam :  Please use :latest tag which is build by Panagis yesterday.. 

Also I would like to inform you that in tag 0.8.5 there is some external dependency issue which is fixed in :latest tag.. 

Panagis will soon update new tag 0.8.6 replica of current latest .. as per discussion with him..

**Comment by pantsel** [comment]
Closing this because it's already been fixed as @mubeennakade pointed out.
