### ISSUE TITLE
[kong v0.11.0] error: Error: EACCES: permission denied, mkdir '/kongadata/'

### ISSUE THREAD

**Issue by dragon28** [pantsel/konga#109]
Hello People,

I found new bug related to the latest committed konga version

npm start

> kongadmin@0.8.6 start /home/dragon/konga
> node --harmony app.js

debug: Hook:api_health_checks:process() called
debug: Hook:health_checks:process() called
debug: Hook:user_events_hook:process() called
debug: Seeding User...
debug: User seed planted
debug: Seeding Kongnode...
debug: Kongnode seed planted
debug: Seeding Emailtransport...
debug: Emailtransport seed planted
error: Bootstrap encountered an error: (see below)
error: Error: EACCES: permission denied, mkdir '/kongadata/'
    at Error (native)
    at /home/dragon/konga/config/bootstrap.js:19:16
    at Array.forEach (native)
    at Object.bootstrap (/home/dragon/konga/config/bootstrap.js:17:10)
    at Sails.runBootstrap (/home/dragon/konga/node_modules/sails/lib/app/private/bootstrap.js:44:25)
    at Sails.wrapper [as runBootstrap] (/home/dragon/konga/node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at Sails.initialize (/home/dragon/konga/node_modules/sails/lib/app/private/initialize.js:68:9)
    at wrapper (/home/dragon/konga/node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at /home/dragon/konga/node_modules/async/lib/async.js:713:13
    at iterate (/home/dragon/konga/node_modules/async/lib/async.js:262:13)
    at /home/dragon/konga/node_modules/async/lib/async.js:274:29
    at /home/dragon/konga/node_modules/async/lib/async.js:44:16
    at /home/dragon/konga/node_modules/async/lib/async.js:718:17
    at /home/dragon/konga/node_modules/async/lib/async.js:167:37
    at /home/dragon/konga/node_modules/sails/lib/app/load.js:184:13
    at /home/dragon/konga/node_modules/async/lib/async.js:52:16
    at /home/dragon/konga/node_modules/async/lib/async.js:548:17
    at /home/dragon/konga/node_modules/async/lib/async.js:542:17
    at _arrayEach (/home/dragon/konga/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/home/dragon/konga/node_modules/async/lib/async.js:541:13)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

I believe it was related to the following files:

konga/config/paths.js:6:    "uploads" : ( process.env.STORAGE_PATH || '/kongadata/' )+ 'uploads/'

konga/config/connections.js:31:    filePath:  process.env.NODE_ENV == 'test' ? './.tmp/' : ( process.env.STORAGE_PATH || '/kongadata/' ),

konga/config/bootstrap.js:14:    var dirs = [( process.env.STORAGE_PATH || '/kongadata/' ), ( process.env.STORAGE_PATH || '/kongadata/' )+ 'uploads']

Thanks

**Comment by pantsel** [comment]
@dragon28 , this is not a bug. You will just have to define the storage path yourself to a directory konga will have access persmissions via the env var <code>STORAGE_PATH </code> as you see in the logs

**Comment by pantsel** [comment]
@dragon28 , this implementation will change in the upcoming version.

**Comment by dragon28** [comment]
@pantsel

Thank you very much

Manage to get it work after executing  the following command

export STORAGE_PATH=$HOME/konga

Thanks
