### ISSUE TITLE
User signup email url invalid

### ISSUE THREAD

**Issue by Luncher** [pantsel/konga#134]
![1511329434043](https://user-images.githubusercontent.com/5138977/33111869-da0d68be-cf15-11e7-8d07-a80ed1525c29.jpg)

The Url prefix is `undefined`

**Comment by Luncher** [comment]
I find the baseUrl config  
![1511330072078](https://user-images.githubusercontent.com/5138977/33112154-57b1239a-cf17-11e7-9baf-a44d36970b19.jpg)

I don't know what baseUrl means

**Comment by pantsel** [comment]
It's the base url the Konga runs on.

For example if it's on localhost it would be
<code>http://localhost:1337</code>

If it's on a subdomain it would be like
<code>http://subdomain.mydomain.com</code>

You get the vibe.

**Comment by Luncher** [comment]
Why the default baseUrl is not the domain name of the current Konga?

**Comment by pantsel** [comment]
that is what you should write

**Comment by Luncher** [comment]
![1511345953283](https://user-images.githubusercontent.com/5138977/33122245-50d7c996-cf3c-11e7-8c9d-7cd27d0d5a05.jpg)

If left blank,  `ip:port` will be used...

**Comment by Luncher** [comment]
```javascript

{
originalError: {
name: "error",
length: 185,
severity: "ERROR",
code: "42703",
hint: "Perhaps you meant to reference the column "konga_users.active".",
position: "472",
file: "parse_relation.c",
line: "3293",
routine: "errorMissingColumn"
},
_e: {
name: "error",
length: 185,
severity: "ERROR",
code: "42703",
hint: "Perhaps you meant to reference the column "konga_users.active".",
position: "472",
file: "parse_relation.c",
line: "3293",
routine: "errorMissingColumn"
},
rawStack: "error: column konga_users.activated does not exist at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11) at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17) at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22) at emitOne (events.js:96:13) at Socket.emit (events.js:188:7) at readableAddChunk (_stream_readable.js:176:18) at TCP.onread (net.js:547:20)",
details: "Details: error: column konga_users.activated does not exist ",
message: "[Error (E_UNKNOWN) Encountered an unexpected error] Details: error: column konga_users.activated does not exist ",
stack: "Error (E_UNKNOWN) :: Encountered an unexpected error error: column konga_users.activated does not exist at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11) at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17) at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22) at emitOne (events.js:96:13) at Socket.emit (events.js:188:7) at readableAddChunk (_stream_readable.js:176:18) at TCP.onread (net.js:547:20)"
}

```

when I click activation link error prompt...

**Comment by pantsel** [comment]
OK, there might be a typo there. I will check it out.
