### ISSUE TITLE
Send Active Account Email Error

### ISSUE THREAD

**Issue by Luncher** [pantsel/konga#141]
```shell

konga_konga.1.vfwbqp6we7vfkslsxfg5cxyt2 | 2017-11-27T01:59:49.112347645Z user-events:notify:error Error: connect ECONNREFUSED 127.0.0.1:587
konga_konga.1.vfwbqp6we7vfkslsxfg5cxyt2 | 2017-11-27T01:59:49.112472649Z     at Object.exports._errnoException (util.js:1020:11)
konga_konga.1.vfwbqp6we7vfkslsxfg5cxyt2 | 2017-11-27T01:59:49.112483054Z     at exports._exceptionWithHostPort (util.js:1043:20)
konga_konga.1.vfwbqp6we7vfkslsxfg5cxyt2 | 2017-11-27T01:59:49.112488728Z     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

```

**Comment by Luncher** [comment]
Maybe there's something wrong with my operation. I closed the issue.
