### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by jeremyjpj0916** [pantsel/konga#152]
Terminal Log I see this:

```
Error: The hook `grunt` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.grunt._hookTimeout to a higher value (currently 60000)
    at Timeout.tooLong [as _onTimeout] (/app/node_modules/sails/lib/app/private/loadHooks.js:85:21)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
/app/node_modules/sails-mysql/lib/adapter.js:58
      if (evName === 'error') { throw data; }
                                ^

AdapterError: Invalid connection name specified
    at getConnectionObject (/app/node_modules/sails-mysql/lib/adapter.js:1211:35)
    at spawnConnection (/app/node_modules/sails-mysql/lib/adapter.js:1126:7)
    at Object.update (/app/node_modules/sails-mysql/lib/adapter.js:958:16)
    at update (/app/node_modules/waterline/lib/waterline/adapter/dql.js:239:13)
    at child.updateRecords (/app/node_modules/waterline/lib/waterline/query/dql/update.js:208:16)
    at /app/node_modules/waterline/lib/waterline/query/dql/update.js:58:21
    at /app/node_modules/waterline/node_modules/async/lib/async.js:726:13
    at /app/node_modules/waterline/node_modules/async/lib/async.js:52:16
    at /app/node_modules/waterline/node_modules/async/lib/async.js:269:32
    at /app/node_modules/waterline/node_modules/async/lib/async.js:44:16
    at /app/node_modules/waterline/node_modules/async/lib/async.js:723:17
    at /app/node_modules/waterline/node_modules/async/lib/async.js:167:37
    at /app/node_modules/waterline/node_modules/async/lib/async.js:52:16
    at /app/node_modules/waterline/node_modules/async/lib/async.js:269:32
    at /app/node_modules/waterline/node_modules/async/lib/async.js:44:16
    at child.<anonymous> (/app/node_modules/waterline/lib/waterline/utils/schema.js:152:44)
    at fn (/app/node_modules/waterline/lib/waterline/utils/callbacksRunner.js:79:10)
    at /app/node_modules/waterline/node_modules/async/lib/async.js:181:20
    at iterate (/app/node_modules/waterline/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/app/node_modules/waterline/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/app/node_modules/waterline/node_modules/async/lib/async.js:214:22)
    at Object.runner.beforeUpdate (/app/node_modules/waterline/lib/waterline/utils/callbacksRunner.js:82:9)
    at /app/node_modules/waterline/lib/waterline/query/dql/update.js:175:17
    at /app/node_modules/waterline/node_modules/async/lib/async.js:718:13
    at iterate (/app/node_modules/waterline/node_modules/async/lib/async.js:262:13)
    at /app/node_modules/waterline/node_modules/async/lib/async.js:274:29
    at /app/node_modules/waterline/node_modules/async/lib/async.js:44:16
    at /app/node_modules/waterline/node_modules/async/lib/async.js:723:17
    at /app/node_modules/waterline/node_modules/async/lib/async.js:167:37
    at /app/node_modules/sails-hook-validation/lib/validate.js:45:21
    at /app/node_modules/waterline/lib/waterline/query/validate.js:80:7
    at /app/node_modules/waterline/node_modules/async/lib/async.js:726:13
    at /app/node_modules/waterline/node_modules/async/lib/async.js:52:16
at /app/node_modules/waterline/node_modules/async/lib/async.js:269:32

```

Not sure what is going on, only recently did I add a liveness probe to the app with these details:

 livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /#!/login
              port: 1337
              scheme: HTTPS
            initialDelaySeconds: 300
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5

Supposedly this should hit the login page after waiting 300 seconds on konga to launch and every 30 seconds it makes sure that login page works with 10 second timeout delay on the page load..

EDIT, i may have to rethink how i probe to make sure konga is up, my container has restarted 600 times the last 2 days so i think the liveness probe and konga do not play nice. Might just remove liveness probe all together.

**Comment by pantsel** [comment]
@jeremyjpj0916 , try setting env var  `KONGA_HOOK_TIMEOUT` to something like 120000.

In some cases the gulp tasks take too long to load. This has to do with the server performance as well.

**Comment by jeremyjpj0916** [comment]
Done and the issue is not revealing itself any longer, if anyone wants a helpful hint for a liveness probe against konga that will work I altered to this now and it seems fine:

```
livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 1337
              scheme: HTTP
            initialDelaySeconds: 300
            periodSeconds: 30
            successThreshold: 1
timeoutSeconds: 5
```
