### ISSUE TITLE
SMTP connection failed.

### ISSUE THREAD

**Issue by jeremyjpj0916** [pantsel/konga#154]
Seems to be cert related? Thoughts?

Is it a matter of konga app not allowing my companies internal self-signed cert upon connecting to the smtp relay server? If so is there an environment variable and a nice place you recommend storing our crt/key files?

Maybe setting NODE_TLS_REJECT_UNAUTHORIZED=0 as an environment variable would do the trick?

```
Sending 500 ("Server Error") response: 
 { error: 
   { Error: self signed certificate in certificate chain
       at Error (native)
       at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
       at emitNone (events.js:86:13)
       at TLSSocket.emit (events.js:185:7)
       at TLSSocket._finishInit (_tls_wrap.js:610:8) code: 'SELF_SIGNED_CERT_IN_CHAIN' } }
Health_checks:notify:error Error: Missing credentials for "PLAIN"
    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:591:19)
    at SMTPConnection.login (/app/node_modules/nodemailer/lib/smtp-connection/index.js:340:38)
    at connection.connect (/app/node_modules/nodemailer/lib/smtp-transport/index.js:270:32)
    at SMTPConnection.once (/app/node_modules/nodemailer/lib/smtp-connection/index.js:188:17)
    at SMTPConnection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at SMTPConnection.emit (events.js:185:7)
    at SMTPConnection._actionEHLO (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1113:14)
    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:747:20)
    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:543:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TCP.onread (net.js:547:20)
KongProxyController request error undefined
```

**Comment by jeremyjpj0916** [comment]
Seems the ENV variable gets me a step closer to ignore TLS, say my SMTP server does not support AUTH as it responds to konga letting me know that:
"notify:error Error: Invalid login: 503 #5.3.3 AUTH not available"

Is there any env variable or way I can get this nodemailer tool you integrated to not pass PLAIN, but a type that does not require user/pass?

"
Health_checks:notify:error Error: Missing credentials for "PLAIN"
    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:591:19)
    at SMTPConnection.login (/app/node_modules/nodemailer/lib/smtp-connection/index.js:340:38)
    at connection.connect (/app/node_modules/nodemailer/lib/smtp-transport/index.js:270:32)
    at SMTPConnection.once (/app/node_modules/nodemailer/lib/smtp-connection/index.js:188:17)
    at SMTPConnection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at SMTPConnection.emit (events.js:185:7)
    at SMTPConnection._actionEHLO (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1113:14)
    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:747:20)
    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:543:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
at TCP.onread (net.js:547:20)
"

Thanks.

**Comment by jeremyjpj0916** [comment]
Decided not to use konga for notifications, have other tools already so closing this as its not important and might be more specific to my companies smtp settings.

**Comment by ardimac** [comment]
i got the error like this

KongProxyController request error undefined
Sending 500 ("Server Error") response:
 { error:
   { Error: connect ECONNREFUSED 36.66.192.45:8001
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
     errno: 'ECONNREFUSED',
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '36.66.192.45',
     port: 8001 } }
