### ISSUE TITLE
erro in start konga

### ISSUE THREAD

**Issue by gpmmelo** [pantsel/konga#241]
I am following instructions but not work configuration default. 

Version Linux: 
Ubuntu 16.04.4 LTS \n \l

node --version
v4.2.6

npm --version
3.5.2

used this command but same error:  

./start.sh or npm start

No DB Adapter defined. Using localDB...
error: `include-all` attempted to `require(/opt/konga/api/hooks/api-health-checks.js)`, but an error occurred:: 
Details:TypeError: ["true","yes","y","1"].includes is not a function
    at Object.<anonymous> (/opt/konga/node_modules/nodemailer/lib/nodemailer.js:16:50)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/konga/api/events/api-health-checks.js:14:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/konga/api/hooks/api-health-checks.js:3:25)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /opt/konga/node_modules/include-all/lib/help-include-all-sync.js:271:33

**Comment by pantsel** [comment]
@gpmmelo , try upgrading node to the LTS 8.11.3
