### ISSUE TITLE
come across issue for init db

### ISSUE THREAD

**Issue by xiaods** [pantsel/konga#254]
```
$ docker run --rm pantsel/konga:next -c prepare -a mysql -u mysql://bitbook:Aa888888@127.0.0.1:3307/monga
debug: Preparing database...
Using MySQL DB Adapter.
Creating database `monga` if not exists.
{ Error: connect ECONNREFUSED 127.0.0.1:3307
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
    --------------------
    at Protocol._enqueue (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/app/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:123:18)
    at Connection._implyConnect (/app/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:454:10)
    at Connection.query (/app/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:199:8)
    at Object.create (/app/makedb/dbs/mysql.js:51:20)
    at Object.run (/app/makedb/dbs/mysql.js:29:21)
    at module.exports (/app/makedb/index.js:15:43)
    at Object.<anonymous> (/app/bin/konga.js:56:23)
    at Module._compile (module.js:652:30)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3307,
  fatal: true }
```
anyone can do me a favor?

**Comment by pantsel** [comment]
@xiaods , it seems that your db is not accessible from the network Konga belongs using 127.0.0.1.
I will need more details about your setup because what you posted doesn't provide much information except that the connection to your server @ 127.0.0.1:3307 was refused.

**Comment by pantsel** [comment]
Try `localhost` or your public IP instead of 127.0.0.1.
Also make sure the port is correct. It was `3307` before and now it's `3306`?

**Comment by xiaods** [comment]
@pantsel yes,  currently my laptop's mysql use 3306, not 3307.

```
xiaods at xiaodeshi in ~/Documents/code/bitbook-projects/konga on master*
$ ip a
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	inet 127.0.0.1/8 lo0
	inet6 ::1/128
	inet6 fe80::1/64 scopeid 0x1
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1453
	ether 60:f8:1d:ac:c9:d0
	inet6 fe80::1088:1dab:6f95:8ed5/64 secured scopeid 0x4
	inet 192.168.1.5/24 brd 192.168.1.255 en0
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	ether fe:f2:fc:0c:ee:c6
	inet6 fe80::fcf2:fcff:fe0c:eec6/64 scopeid 0x8
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::88b4:2714:84bf:e586/64 scopeid 0xa
xiaods at xiaodeshi in ~/Documents/code/bitbook-projects/konga on master*
$ docker run --rm pantsel/konga:next -c prepare -a mysql -u mysql://root:@192.168.1.5:3306/monga
debug: Preparing database...
Using MySQL DB Adapter.
Creating database `monga` if not exists.
{ Error: connect ECONNREFUSED 192.168.1.5:3306
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
    --------------------
    at Protocol._enqueue (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/app/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:123:18)
    at Connection._implyConnect (/app/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:454:10)
    at Connection.query (/app/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:199:8)
    at Object.create (/app/makedb/dbs/mysql.js:51:20)
    at Object.run (/app/makedb/dbs/mysql.js:29:21)
    at module.exports (/app/makedb/index.js:15:43)
    at Object.<anonymous> (/app/bin/konga.js:56:23)
    at Module._compile (module.js:652:30)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.5',
  port: 3306,
  fatal: true }
```

**Comment by xiaods** [comment]
```
$ telnet 127.0.0.1 3306
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
J
5.7.2;J=bua?!zOB0B%7MQmysql_native_password



^C^CConnection closed by foreign host.
```

**Comment by xiaods** [comment]
don't know what reason caused that. but i can manually connected to mysql instance. but the js it not working for me. do you have some way to print sql in raw, i can manually create the tables with plain sql.

**Comment by pantsel** [comment]
If I got it correctly, you have mysql installed on your pc and tried to install Konga to a docker container.

The problem is that when you refer to 127.0.0.1 from Konga's container, you refer to the containers localhost and not the server's where mysql is installed. 

Konga's container must be in the same network with the mysql instance.

**Comment by xiaods** [comment]
@pantsel thanks for your help. i got it done. because macos's mysql config is bind 127.0.0.1, not external ip. so it caused me failed. i restart mysql service with https://dba.stackexchange.com/questions/55958/cant-remote-access-mysql-server-running-on-mac-os-x, it works like a charms.
