### ISSUE TITLE
Detect incorrect version of node.js and report with "nice" error message.

### ISSUE THREAD

**Issue by smklugherz** [pantsel/konga#259]
When attempting to perform the DB prep steps. We receive the error that controllers failed to load.

node /app/bin/konga.js prepare --adapter postgres --uri postgresql://postgresql/konga?user=*****&password=*****

Failed to lift Sails: { `include-all` attempted to `require(/app/api/controllers/KongRoutesController.js)`, but an error occurred::
Details:/app/api/controllers/KongRoutesController.js:14
  consumers: async (req,res) => {

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /app/node_modules/include-all/lib/help-include-all-sync.js:271:33
    at Array.forEach (native)
    at _recursivelyIncludeAll (/app/node_modules/include-all/lib/help-include-all-sync.js:174:11)
    at includeAll (/app/node_modules/include-all/lib/help-include-all-sync.js:292:5)
    at helpBuildDictionary (/app/node_modules/include-all/lib/help-build-dictionary.js:43:15)
    at Function.module.exports.optional (/app/node_modules/include-all/index.js:67:10)
    at Hook.loadControllers (/app/node_modules/sails/lib/hooks/moduleloader/index.js:324:18)
    at Hook.wrapper [as loadControllers] (/app/node_modules/@sailshq/lodash/lib/index.js:3275:19)
    at Hook.loadAndRegisterControllers (/app/node_modules/sails/lib/hooks/controllers/to-load-and-register-controllers.js:33:19)
    at Hook.initialize (/app/node_modules/sails/lib/hooks/controllers/index.js:59:12)
    at Hook.wrapper [as initialize] (/app/node_modules/@sailshq/lodash/lib/index.js:3275:19)
    at /app/node_modules/sails/lib/hooks/index.js:88:16
    at /app/node_modules/async/lib/async.js:52:16
    at /app/node_modules/async/lib/async.js:548:17
    at /app/node_modules/async/lib/async.js:542:17
    at _arrayEach (/app/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/app/node_modules/async/lib/async.js:541:13)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
  originalErrorCode: undefined,
  code: 'include-all:COULD_NOT_REQUIRE' }

**Comment by smklugherz** [comment]
That fixed it. I may be helpful to having a "nice" error if using an incompatible version of node.

**Comment by pantsel** [comment]
Will do
