### ISSUE TITLE
connect to kong admin fail

### ISSUE THREAD

**Issue by kkxxr66573** [pantsel/konga#274]
error: KongProxyController request error undefined
error: Sending 500 ("Server Error") response:
 { error:
   { Error: connect ECONNREFUSED 127.0.0.1:8001
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 8001 } }

**Comment by pantsel** [comment]
@kkxxr66573 , it seems that 127.0.0.1:8001 is not accessible. This doesn't seem to be an issue with Konga.
Make sure that Kong's admin api is accessible from 127.0.0.1:8001.

What is the connecton url you have setup in Konga?

**Comment by pantsel** [comment]
Closing due to inactivity

**Comment by prajwalahluwalia** [comment]
same issue

**Comment by gtpan77** [comment]
If you are konga in docker on localhost and trying to access kong running on localhost, then don't use localhost. Instead, use host.docker.internal (works on mac, windows). for further info [check](https://stackoverflow.com/a/43541732/5646269)
