### ISSUE TITLE
0.13.0 Issue Hook taking too long

### ISSUE THREAD

**Issue by grillorafael** [pantsel/konga#284]
```
[31merror: [39mError: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 60000)
    at Timeout.tooLong [as _onTimeout] (/app/node_modules/sails/lib/app/private/loadHooks.js:85:21)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
[31merror: [39mA hook (`orm`) failed to load!
/app/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /app/node_modules/async/lib/async.js:43:36
    at /app/node_modules/sails/lib/app/private/loadHooks.js:99:18
    at /app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:52:16
    at /app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:570:21
    at /app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:167:37
    at /app/node_modules/sails-hook-orm/lib/initialize.js:389:27
    at _afterInitializingWaterline (/app/node_modules/sails-hook-orm/lib/build-waterline-ontology.js:99:25)
    at /app/node_modules/waterline/lib/waterline.js:226:23
    at /app/node_modules/waterline/node_modules/async/lib/async.js:52:16
    at /app/node_modules/waterline/node_modules/async/lib/async.js:264:21
    at /app/node_modules/waterline/node_modules/async/lib/async.js:44:16
    at /app/node_modules/waterline/lib/waterline/query/index.js:68:23
    at afterDescribe (/app/node_modules/waterline/lib/waterline/adapter/sync/strategies/alter.js:35:21)
    at wrapper (/app/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/app/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/app/node_modules/waterline/lib/waterline/utils/normalize.js:335:16)
    at error (/app/node_modules/waterline/node_modules/switchback/lib/normalize.js:42:31)
    at _switch (/app/node_modules/waterline/node_modules/switchback/lib/factory.js:56:28)
    at spawnConnection (/app/node_modules/sails-postgresql/lib/adapter.js:1168:34)
    at Object.describe (/app/node_modules/sails-postgresql/lib/adapter.js:155:7)
    at module.exports.describe (/app/node_modules/waterline/lib/waterline/adapter/ddl/index.js:79:13)
    at module.exports [as migrateAlter] (/app/node_modules/waterline/lib/waterline/adapter/sync/strategies/alter.js:33:8)
    at child.Query.sync (/app/node_modules/waterline/lib/waterline/query/index.js:67:37)
    at /app/node_modules/waterline/lib/waterline.js:296:16
    at /app/node_modules/waterline/node_modules/async/lib/async.js:181:20
    at iterate (/app/node_modules/waterline/node_modules/async/lib/async.js:262:13)
    at /app/node_modules/waterline/node_modules/async/lib/async.js:274:29
    at /app/node_modules/waterline/node_modules/async/lib/async.js:44:16
```

I'm upgrading from 0.12 and sometimes when it works I see the following error trying to activate the kong connection through the UI:

```
/app/api/controllers/UserController.js:48
                if(user.node) {
                        ^

TypeError: Cannot read property 'node' of undefined
    at /app/api/controllers/UserController.js:48:25
    at wrapper (/app/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/app/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/app/node_modules/waterline/lib/waterline/utils/normalize.js:324:18)
    at success (/app/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/app/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at /app/node_modules/waterline/lib/waterline/query/dql/update.js:235:9
    at /app/node_modules/waterline/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/app/node_modules/waterline/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/app/node_modules/waterline/node_modules/async/lib/async.js:209:22)
    at /app/node_modules/waterline/lib/waterline/query/dql/update.js:226:13
    at child.updatedNestedAssociations (/app/node_modules/waterline/lib/waterline/query/dql/update.js:263:12)
    at /app/node_modules/waterline/lib/waterline/query/dql/update.js:223:31
    at wrapper (/app/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/app/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/app/node_modules/waterline/lib/waterline/utils/normalize.js:324:18)
    at success (/app/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/app/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at afterwards (/app/node_modules/waterline/lib/waterline/adapter/dql.js:244:14)
    at wrapper (/app/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/app/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/app/node_modules/waterline/lib/waterline/utils/normalize.js:324:18)
    at success (/app/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/app/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at /app/node_modules/sails-postgresql/lib/adapter.js:1296:16
    at Query.__UPDATE__ [as callback] (/app/node_modules/sails-postgresql/lib/adapter.js:1082:11)
    at Query.handleReadyForQuery (/app/node_modules/sails-postgresql/node_modules/pg/lib/query.js:89:10)
    at Connection.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/client.js:163:19)
I0930 12:45:22.388418 1887087 executor.cpp:675] Container exited with status 1
W0930 12:45:22.388418 1887080 logging.cpp:93] RAW: Received signal SIGTERM from process 1783449 of user 0; exiting
/app/api/controllers/UserController.js:48
                if(user.node) {
                        ^

TypeError: Cannot read property 'node' of undefined
    at /app/api/controllers/UserController.js:48:25
    at wrapper (/app/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/app/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/app/node_modules/waterline/lib/waterline/utils/normalize.js:324:18)
    at success (/app/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/app/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at /app/node_modules/waterline/lib/waterline/query/dql/update.js:235:9
    at /app/node_modules/waterline/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/app/node_modules/waterline/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/app/node_modules/waterline/node_modules/async/lib/async.js:209:22)
    at /app/node_modules/waterline/lib/waterline/query/dql/update.js:226:13
    at child.updatedNestedAssociations (/app/node_modules/waterline/lib/waterline/query/dql/update.js:263:12)
    at /app/node_modules/waterline/lib/waterline/query/dql/update.js:223:31
    at wrapper (/app/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/app/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/app/node_modules/waterline/lib/waterline/utils/normalize.js:324:18)
    at success (/app/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/app/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at afterwards (/app/node_modules/waterline/lib/waterline/adapter/dql.js:244:14)
    at wrapper (/app/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/app/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/app/node_modules/waterline/lib/waterline/utils/normalize.js:324:18)
    at success (/app/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/app/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at /app/node_modules/sails-postgresql/lib/adapter.js:1296:16
    at Query.__UPDATE__ [as callback] (/app/node_modules/sails-postgresql/lib/adapter.js:1082:11)
    at Query.handleReadyForQuery (/app/node_modules/sails-postgresql/node_modules/pg/lib/query.js:89:10)
    at Connection.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/client.js:163:19)
I0930 12:45:22.388418 1887087 executor.cpp:675] Container exited with status 1
W0930 12:45:22.388418 1887080 logging.cpp:93] RAW: Received signal SIGTERM from process 1783449 of user 0; exiting
/app/api/controllers/UserController.js:48
                if(user.node) {
                        ^

TypeError: Cannot read property 'node' of undefined
    at /app/api/controllers/UserController.js:48:25
    at wrapper (/app/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/app/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/app/node_modules/waterline/lib/waterline/utils/normalize.js:324:18)
    at success (/app/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/app/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at /app/node_modules/waterline/lib/waterline/query/dql/update.js:235:9
    at /app/node_modules/waterline/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/app/node_modules/waterline/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/app/node_modules/waterline/node_modules/async/lib/async.js:209:22)
    at /app/node_modules/waterline/lib/waterline/query/dql/update.js:226:13
    at child.updatedNestedAssociations (/app/node_modules/waterline/lib/waterline/query/dql/update.js:263:12)
    at /app/node_modules/waterline/lib/waterline/query/dql/update.js:223:31
    at wrapper (/app/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/app/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/app/node_modules/waterline/lib/waterline/utils/normalize.js:324:18)
    at success (/app/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/app/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at afterwards (/app/node_modules/waterline/lib/waterline/adapter/dql.js:244:14)
    at wrapper (/app/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/app/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/app/node_modules/waterline/lib/waterline/utils/normalize.js:324:18)
    at success (/app/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/app/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at /app/node_modules/sails-postgresql/lib/adapter.js:1296:16
    at Query.__UPDATE__ [as callback] (/app/node_modules/sails-postgresql/lib/adapter.js:1082:11)
    at Query.handleReadyForQuery (/app/node_modules/sails-postgresql/node_modules/pg/lib/query.js:89:10)
    at Connection.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/client.js:163:19)
```

**Comment by pantsel** [comment]
Hey Rafael, try setting KONGA_HOOK_TIMEOUT env var to 120000. Check out the FAQ section of the README.md

**Comment by jeremyjpj0916** [comment]
Slightly chuckled at grill or a fael username and you came to the conclusion of him being Rafael Pantsel 😄 . https://www.urbandictionary.com/define.php?term=grill

**Comment by pantsel** [comment]
Seemed logical and Spanish :)

**Comment by grillorafael** [comment]
Just to give a heads up that everything seems to be working fine so the issue can be closed. About the user it is a mix of name + surname (Rafael + Grillo) :)

**Comment by pantsel** [comment]
Ha! So i was right!

**Comment by jeremyjpj0916** [comment]
Darn! I have been wrong all this time about your username in kong/konga all this time @grillorafael Pantsel 1 Point, Jeremy 0 😆  .

**Comment by anigkus** [comment]
> Hey Rafael, try setting KONGA_HOOK_TIMEOUT env var to 120000. Check out the FAQ section of the README.md

I'm setting `KONGA_HOOK_TIMEOUT`,has error:

```
# ls -al | grep .env
-rw-r--r--.   1 root root    225 May 27 01:21 .env
-rw-r--r--.   1 root root    225 May 26 14:31 .env_example
# cat .env
PORT=1337
NODE_ENV=production
KONGA_HOOK_TIMEOUT=120000
DB_ADAPTER=postgres
DB_URI=postgresql://localhost:5432/konga
DB_USER=konga
DB_PASSWORD=konga123456
DB_DATABASE=konga
KONGA_LOG_LEVEL=warn
TOKEN_SECRET=some_secret_token
```

```
# node ./bin/konga.js  prepare --adapter postgres --uri postgresql://localhost:5432/konga
Preparing database...
(node:475025) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
error: Failed to prepare database: Error: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 60000)
    at Timeout.tooLong [as _onTimeout] (/root/konga/node_modules/sails/lib/app/private/loadHooks.js:85:21)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

# postgresql  DB is ok.
```
# telnet localhost 5432
Trying ::1...
Connected to localhost.
Escape character is '^]'.
^CConnection closed by foreign host.
```
