### ISSUE TITLE
Konga container gets killed with ReferenceError: uid is not defined

### ISSUE THREAD

**Issue by envy7** [pantsel/konga#307]
Attempted to connect Konga container to authenticate using ldap, docker container dies with this error:

`lodash.templateSources[0]:9
((__t = (uid)) == null ? '' : __t) +
^

ReferenceError: uid is not defined
at eval (lodash.templateSources[0]:9:10)
at Object.groupSearchFilter (/app/config/ldap.js:19:20)
at LdapAuth._findGroups (/app/node_modules/ldapauth-fork/lib/ldapauth.js:311:32)
at /app/node_modules/ldapauth-fork/lib/ldapauth.js:366:12
at sendResult (/app/node_modules/ldapjs/lib/client/client.js:1395:12)
at messageCallback (/app/node_modules/ldapjs/lib/client/client.js:1421:16)
at Parser.onMessage (/app/node_modules/ldapjs/lib/client/client.js:1089:14)
at emitOne (events.js:116:13)
at Parser.emit (events.js:211:7)
at Parser.write (/app/node_modules/ldapjs/lib/messages/parser.js:111:8)
at Socket.onData (/app/node_modules/ldapjs/lib/client/client.js:1076:22)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
at TCP.onread (net.js:597:20)
I1126 20:14:13.318116 87782 executor.cpp:736] Container exited with status 1
I1126 20:14:14.318631 87813 process.cpp:926] Stopped the socket accept loop`

**Comment by envy7** [comment]
Attempted to connect Konga container to authenticate using ldap, docker container dies with this error:

`lodash.templateSources[0]:9
((__t = (uid)) == null ? '' : __t) +
         ^

ReferenceError: uid is not defined
    at eval (lodash.templateSources[0]:9:10)
    at Object.groupSearchFilter (/app/config/ldap.js:19:20)
    at LdapAuth._findGroups (/app/node_modules/ldapauth-fork/lib/ldapauth.js:311:32)
    at /app/node_modules/ldapauth-fork/lib/ldapauth.js:366:12
    at sendResult (/app/node_modules/ldapjs/lib/client/client.js:1395:12)
    at messageCallback (/app/node_modules/ldapjs/lib/client/client.js:1421:16)
    at Parser.onMessage (/app/node_modules/ldapjs/lib/client/client.js:1089:14)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser.write (/app/node_modules/ldapjs/lib/messages/parser.js:111:8)
    at Socket.onData (/app/node_modules/ldapjs/lib/client/client.js:1076:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
I1126 20:14:13.318116 87782 executor.cpp:736] Container exited with status 1
I1126 20:14:14.318631 87813 process.cpp:926] Stopped the socket accept loop`

**Comment by pantsel** [comment]
@envy7 ,
sorry for the late response. The LDAP integration is still buggy and not working as expected.

I'll see to it as soon as i manage to make Konga compatible with Kong 1.x.

**Comment by TFarla** [comment]
Any updates on this? I'm also facing the issue as described above.

**Comment by pantsel** [comment]
@TFarla , not yet. Kong 1.x compatibility took some time. Just released the compatible version yesterday. This one will be on my next batch of fixes.

**Comment by TFarla** [comment]
Thanks for the quick response! I'm a bit embarrassed to admit the issue was due to a misconfiguration on my part. I was using the `KONGA_LDAP_USER_ATTRS` with values `email` while the ldap configuration expects at least a uid and uidNumber. Using the default value for `KONGA_LDAP_USER_ATTRS` fixed the issue for me.

**Comment by pantsel** [comment]
Closing this due to inactivity. If the issue persists in the newer versions, feel free to reopen.
