### ISSUE TITLE
the latest version konga install error 

### ISSUE THREAD

**Issue by ophusky** [pantsel/konga#332]
[root@kong-m100-201 konga]# npm --version
5.6.0
[root@kong-m100-201 konga]# node --version
v8.11.3

[root@kong-m100-201 konga]# npm i
> typechecker@2.0.8 preinstall /home/coremail/files/konga/node_modules/extendr/node_modules/typechecker
> node ./cyclic.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/home/coremail/files/konga/node_modules/extendr/node_modules/typechecker/cyclic.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typechecker@2.0.8 preinstall: `node ./cyclic.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the typechecker@2.0.8 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-17T15_51_37_463Z-debug.log

**Comment by pantsel** [comment]
have you resolved this?

**Comment by pantsel** [comment]
Closing this due to inactivity. Feel free to repopen if needed.

**Comment by ophusky** [comment]
> have you resolved this?

no, It seems that the error still exists...

**Comment by ophusky** [comment]
> have you resolved this?

when I  use
```
sudo npm i
```
this error does not appear again，thank you.
