### ISSUE TITLE
Database creation fails on Postgre

### ISSUE THREAD

**Issue by christophelec** [pantsel/konga#342]
Hello,

While trying to use Konga on a postgre DB that does not already exists, I get the following error :
```
Failed to create `konga` { error: syntax error at or near "`"
    at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
```

I'm using the following env variable to set the DB name : DB_DATABASE=konga

I suspect the issue is related to the following commit :
https://github.com/pantsel/konga/commit/05bf687d338457c2eaec2176dc0b4bde6e8e2e42#comments

As it seems @acerioni has the same issue as me.

I'm using the official konga docker image : pantsel/konga, with an official postgre image : postgres:9.6.5

Regards,

**Comment by christophelec** [comment]
After a quick try, switching to the 0.14.1 Docker image instead of latest for Konga solves the issue
