### ISSUE TITLE
postgress db creation error

### ISSUE THREAD

**Issue by lukasa1993** [pantsel/konga#345]
```
2019-03-01T11:53:21.136356754Z Database `konga` does not exist. Creating...
2019-03-01T11:53:21.210337634Z Failed to create `konga` { error: syntax error at or near "`"
2019-03-01T11:53:21.210362599Z     at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
2019-03-01T11:53:21.210367772Z     at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
2019-03-01T11:53:21.210370024Z     at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
2019-03-01T11:53:21.210372483Z     at emitOne (events.js:116:13)
2019-03-01T11:53:21.210418686Z     at Socket.emit (events.js:211:7)
2019-03-01T11:53:21.210422840Z     at addChunk (_stream_readable.js:263:12)
2019-03-01T11:53:21.210424873Z     at readableAddChunk (_stream_readable.js:250:11)
2019-03-01T11:53:21.210426843Z     at Socket.Readable.push (_stream_readable.js:208:10)
2019-03-01T11:53:21.210428755Z     at TCP.onread (net.js:601:20)
```

```
bash-4.4# postgres -V
postgres (PostgreSQL) 11.2
```

trying to create fresh db from docker. i think ` needs to be removed

```
client.query('CREATE DATABASE `' + opts.database + '`', function (err, res) {
```
here at makedb/dbs/pg.js:122

**Comment by pantsel** [comment]
@lukasa1993 , use the latest stable version and not the master branch.

https://github.com/pantsel/konga/releases/tag/0.14.1
or
docker pull pantsel/konga:0.14.1

**Comment by lukasa1993** [comment]
i am using latest docker tag, is it pushed there?

**Comment by pantsel** [comment]
Try repulling the latest docker tag, otherwise use the 0.14.1 which is the latest stable release
