### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by berry2012** [pantsel/konga#377]
Getting the errors below after executing these 3 steps
$ git clone https://github.com/pantsel/konga.git
$ cd konga
$ npm i

make: Leaving directory `/home/ec2-user/konga/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ec2-user/konga/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Linux 4.9.32-15.41.amzn1.x86_64
gyp ERR! command "/home/ec2-user/.nvm/versions/node/v12.1.0/bin/node" "/home/ec2-user/konga/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/ec2-user/konga/node_modules/node-sass
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2019-05-04T12_23_13_428Z-debug.log

**Comment by pantsel** [comment]
@berry2012 , try using the TLS version of node `10.15.3`.

**Comment by berry2012** [comment]
thanks @pantsel 
I read somewhere that node v10 won't work so I didn't try node 10.15.3 

I installed node v9 and used it. Everything works now.

nvm install 9.0.0 #install specific version
nvm list
nvm use v9.0.0

**Comment by dangvanduc90** [comment]
after read the log file of npm
 /home/ec2-user/.npm/_logs/2019-05-04T12_23_13_428Z-debug.log
i see node-sass error
so i run npm i node-sass 
before
npm i
success
