### ISSUE TITLE
Can't prepare database if DB_PG_SCHEMA is set

### ISSUE THREAD

**Issue by slimm609** [pantsel/konga#383]
```
debug: Preparing database...
Using postgres DB Adapter.
Database exists. Continue...

error: A hook (`orm`) failed to load!
/app/bin/konga.js:76
        sails.log.error("Failed to prepare database:",error)
              ^

TypeError: Cannot read property 'log' of undefined
    at callback (/app/bin/konga.js:76:15)
    at /app/node_modules/sails/lib/app/load.js:173:22
    at /app/node_modules/async/lib/async.js:52:16
    at /app/node_modules/async/lib/async.js:565:21
    at /app/node_modules/async/lib/async.js:167:37
    at /app/node_modules/sails/lib/app/load.js:120:23
    at /app/node_modules/async/lib/async.js:721:13
    at /app/node_modules/async/lib/async.js:52:16
    at /app/node_modules/async/lib/async.js:264:21
    at /app/node_modules/async/lib/async.js:44:16
    at /app/node_modules/async/lib/async.js:718:17
    at /app/node_modules/async/lib/async.js:167:37
    at hooksReady (/app/node_modules/sails/lib/app/private/loadHooks.js:189:16)
    at /app/node_modules/async/lib/async.js:721:13
    at /app/node_modules/async/lib/async.js:52:16
    at /app/node_modules/async/lib/async.js:264:21
    at /app/node_modules/async/lib/async.js:44:16
    at /app/node_modules/async/lib/async.js:718:17
    at /app/node_modules/async/lib/async.js:167:37
    at /app/node_modules/async/lib/async.js:52:16
    at done (/app/node_modules/async/lib/async.js:241:17)
    at /app/node_modules/async/lib/async.js:44:16
    at /app/node_modules/sails/lib/app/private/loadHooks.js:99:18
    at /app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:52:16
    at /app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:570:21
    at /app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:167:37
    at /app/node_modules/sails-hook-orm/lib/initialize.js:389:27
    at _afterInitializingWaterline (/app/node_modules/sails-hook-orm/lib/build-waterline-ontology.js:99:25)
```

It runs fine if I unset the DB_PG_SCHEMA variable.   Trying to have it go to a different schema but it is failing.

**Comment by pantsel** [comment]
@slimm609 , what happens if instead of defining DB ENV vars separately you define a DB_URI with the full connection string to PG and the shema as `?currentSchema=myschema`?

**Comment by slimm609** [comment]
`node /app/bin/konga.js prepare --adapter $DB_ADAPTER --uri "postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_DATABASE?currentSchema=$KONG_PG_SCHEMA"`

$KONG_PG_SCHEMA is set to `kong` and it ran the migrations against the `public` schema.  

The users search_path is also set to `kong, public`
