### ISSUE TITLE
konga update service error

### ISSUE THREAD

**Issue by chenxuefeng1207** [pantsel/konga#404]
when I use https to connect kong admin(https://localhost:8444)
everything is ok but when I edit service's description I got error:
`error: Error (E_VALIDATION) :: 1 attribute is invalid
error: duplicate key value violates unique constraint "konga_kong_services_service_id_key"
    at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)

Invalid attributes sent to undefined:
 • service_id
   • A record with that `service_id` already exists (`e4614d2c-0bf0-413d-b551-657a2ea4991a`).`
kong version: 1.2.0
konga image : pantsel/konga:latest

**Comment by chenxuefeng1207** [comment]
kong'db is postgresql

**Comment by pantsel** [comment]
@chenxuefeng1207 , use pantsel/konga:next, until the release makes it to master

**Comment by chenxuefeng1207** [comment]
@pantsel  I try the konga:next but got the same error .

**Comment by chenxuefeng1207** [comment]
@pantsel  I create a new service ant edit it's description is ok ,but for old service is not ok

**Comment by chenxuefeng1207** [comment]
I know the reason ,beacause konga_kong_service's kong_node_id is the primiray key of konga_kong_nodes, so http and https connection is two connect, it's kong_node_id is different,
update the konga_kong_service's kong_node_id for https's kong_node_id,then everything is ok!
