### ISSUE TITLE
Latest build in master seems broken

### ISSUE THREAD

**Issue by MichelinMan** [pantsel/konga#419]
To reproduce clone the repo into a new location and follow the instructions:

$ git clone https://github.com/pantsel/konga.git
$ cd konga
$ npm i
$ npm start

Then go to http://localhost:1337 and you will see that they UI has no styling.

Go ahead and create an admin account and you will also see that they UI is stuck at the message "Neat you created an admin account".
Its not possible to dismiss that message.

Something is wrong...

Thank you,
Ioannis

**Comment by pantsel** [comment]
Hey @MichelinMan , have you tried this?
https://github.com/pantsel/konga#1-getting-blank-page-with-uncaught-referenceerror-angular-is-not-defined

**Comment by MichelinMan** [comment]
Hi @pantsel,

I have added the step to reinstall the bower dependencies which does fix the account creation page, it is now styled as expected.

However when I complete the fields and submit the form I get to a blank page.

This is the output in the console:

ELSLABM-156881:konga iordanidisi$ npm start

> kongadmin@0.14.3 start /Users/iordanidisi/Developer/konga
> node --harmony app.js

No DB Adapter defined. Using localDB...
debug: Hook:api_health_checks:process() called
debug: Hook:health_checks:process() called
debug: Hook:start-scheduled-snapshots:process() called
debug: Hook:upstream_health_checks:process() called
debug: Hook:user_events_hook:process() called
debug: Seeding User...
debug: User seed planted
debug: Seeding Kongnode...
debug: Kongnode seed planted
debug: Seeding Emailtransport...
debug: Emailtransport seed planted
error: ** Grunt :: An error occurred. **
error: 
------------------------------------------------------------------------
Warning: Task "default" not found. 

Aborted due to warnings.
Loading "Gruntfile.js" tasks...ERROR
>> Error: Attempted to `require('/Users/iordanidisi/Developer/konga/tasks/config/sass.js')`, but an error occurred:
>> --
>> Error: Cannot find module 'node-sass'
>> Require stack:
>> - /Users/iordanidisi/Developer/konga/tasks/config/sass.js
>> - /Users/iordanidisi/Developer/konga/node_modules/include-all/lib/help-include-all-sync.js
>> - /Users/iordanidisi/Developer/konga/node_modules/include-all/lib/help-build-dictionary.js
>> - /Users/iordanidisi/Developer/konga/node_modules/include-all/index.js
>> - /Users/iordanidisi/Developer/konga/Gruntfile.js
>> - /Users/iordanidisi/Developer/konga/node_modules/grunt/lib/grunt/task.js
>> - /Users/iordanidisi/Developer/konga/node_modules/grunt/lib/grunt.js
>> - /Users/iordanidisi/Developer/konga/node_modules/sails/node_modules/grunt-cli/bin/grunt
>> - /Users/iordanidisi/Developer/konga/node_modules/sails/lib/hooks/grunt/grunt-wrapper.js
>>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
>>   at Function.Module._load (internal/modules/cjs/loader.js:527:27)
>>   at Module.require (internal/modules/cjs/loader.js:683:19)
>>   at require (internal/modules/cjs/helpers.js:16:16)
>>   at Object.<anonymous> (/Users/iordanidisi/Developer/konga/tasks/config/sass.js:1:14)
>>   at Module._compile (internal/modules/cjs/loader.js:776:30)
>>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
>>   at Module.load (/Users/iordanidisi/Developer/konga/node_modules/grunt/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>   at Function.Module._load (internal/modules/cjs/loader.js:556:12)
>>   at Module.require (internal/modules/cjs/loader.js:683:19)
>>   at require (internal/modules/cjs/helpers.js:16:16)
>>   at /Users/iordanidisi/Developer/konga/node_modules/include-all/lib/help-include-all-sync.js:293:33
>>   at Array.forEach (<anonymous>:null:null)
>>   at _recursivelyIncludeAll (/Users/iordanidisi/Developer/konga/node_modules/include-all/lib/help-include-all-sync.js:178:11)
>>   at includeAll (/Users/iordanidisi/Developer/konga/node_modules/include-all/lib/help-include-all-sync.js:317:5)
>>   at includeAllSync (/Users/iordanidisi/Developer/konga/node_modules/include-all/index.js:27:10)
>>   at loadTasks (/Users/iordanidisi/Developer/konga/Gruntfile.js:46:12)
>>   at Object.module.exports (/Users/iordanidisi/Developer/konga/Gruntfile.js:68:28)
>>   at loadTask (/Users/iordanidisi/Developer/konga/node_modules/grunt/lib/grunt/task.js:315:10)
>>   at Task.task.init (/Users/iordanidisi/Developer/konga/node_modules/grunt/lib/grunt/task.js:434:5)
>>   at Object.grunt.tasks (/Users/iordanidisi/Developer/konga/node_modules/grunt/lib/grunt.js:111:8)
>>   at Object.module.exports [as cli] (/Users/iordanidisi/Developer/konga/node_modules/grunt/lib/grunt/cli.js:27:9)
>>   at Object.<anonymous> (/Users/iordanidisi/Developer/konga/node_modules/sails/node_modules/grunt-cli/bin/grunt:44:20)
>>   at Module._compile (internal/modules/cjs/loader.js:776:30)
>>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
>>   at Module.load (internal/modules/cjs/loader.js:643:32)
>>   at Function.Module._load (internal/modules/cjs/loader.js:556:12)
>>   at Module.require (internal/modules/cjs/loader.js:683:19)
>>   at require (internal/modules/cjs/helpers.js:16:16)
>>   at Object.<anonymous> (/Users/iordanidisi/Developer/konga/node_modules/sails/lib/hooks/grunt/grunt-wrapper.js:10:1)
>>   at Module._compile (internal/modules/cjs/loader.js:776:30)
>>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
>>   at Module.load (internal/modules/cjs/loader.js:643:32)
>>   at Function.Module._load (internal/modules/cjs/loader.js:556:12)
>>   at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
>>   at internal/main/run_main_module.js:17:11
>> 
>> --
------------------------------------------------------------------------

error: Looks like a Grunt error occurred--
error: Please fix it, then **restart Sails** to continue running tasks (e.g. watching for changes in assets)
error: Or if you're stuck, check out the troubleshooting tips below.

error: Troubleshooting tips:
error: 
error:  *-> Are "grunt" and related grunt task modules installed locally?  Run `npm install` if you're not sure.
error: 
error:  *-> You might have a malformed LESS, SASS, CoffeeScript file, etc.
error: 
error:  *-> Or maybe you don't have permissions to access the `.tmp` directory?
error:      e.g., `/Users/iordanidisi/Developer/konga/.tmp` ?
error: 
error:      If you think this might be the case, try running:
error:      sudo chown -R 27388359 /Users/iordanidisi/Developer/konga/.tmp


If there is anything I can help with logs, different baby levels etc, I am happy to help.

Thank you,
Ioannis

**Comment by pantsel** [comment]
For some reason the node saas module is not installed.

The troubleshooting tips are self ecplanatory:

```
error: Troubleshooting tips:
error:
error: *-> Are "grunt" and related grunt task modules installed locally? Run npm install if you're not sure.
error:
error: *-> You might have a malformed LESS, SASS, CoffeeScript file, etc.
error:
error: *-> Or maybe you don't have permissions to access the .tmp directory?
error: e.g., /Users/iordanidisi/Developer/konga/.tmp ?
error:
error: If you think this might be the case, try running:
error: sudo chown -R 27388359 /Users/iordanidisi/Developer/konga/.tmp```

**Comment by MichelinMan** [comment]
Thank you for your help.
The saas node module is the problem.

I run `npm install` and  got this output:

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.2/darwin-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.2/darwin-x64-72_binding.node": 

HTTP error 404 Not Found
```

It looks like this artefact is no longer available under that tag:
`https://github.com/sass/node-sass/releases/tag/v4.9.2`

**Comment by MichelinMan** [comment]
I still don't know why line 41 in `package.json`:
`"node-sass": "^4.9.2",`

resolved to `/darwin-x64-72_binding.node` which then results in a 404

**Comment by pantsel** [comment]
@MichelinMan, I will have to try and reproduce that issue. Seems awkward.

What version of node.js and npm are you using?

**Comment by MichelinMan** [comment]
@pantsel 

Thank you.

```
ELSLABM-156881:~ iordanidisi$ node --version
v12.6.0
ELSLABM-156881:~ iordanidisi$ npm --version
6.9.0
```

**Comment by pantsel** [comment]
Konga uses node 8.12 for its automated builds. You could try that or even node 10.16.0 which is the LTS.

Node 12.6 is pretty new and untested when it comes to Konga

**Comment by MichelinMan** [comment]
Thank you.

I will try with 10.16.0 and if that doesn't resolve it then go down to 8.12.

**Comment by MichelinMan** [comment]
With node version 10.16.0 `npm install` works as expected and Konga works as before.
Note the output in my console where version ^4.9.2 resolved in the -64_binding.node URL, not the 72 as I was seeing before.

Thank you for your help.
Should I close the ticket, or rename it to something relating to node version 12.x ?

```
ELSLABM-156881:konga iordanidisi$ node --version
v10.16.0
ELSLABM-156881:konga iordanidisi$ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!

> node-sass@4.9.2 install /Users/iordanidisi/Developer/konga/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.2/darwin-x64-64_binding.node
Download complete ░⸩ ⠋ :
Binary saved to /Users/iordanidisi/Developer/konga/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Caching binary to /Users/iordanidisi/.npm/node-sass/4.9.2/darwin-x64-64_binding.node
```

**Comment by pantsel** [comment]
@MichelinMan , rename it so I can track it down.

Cheers

**Comment by MichelinMan** [comment]
👍🏻
