### ISSUE TITLE
Support for ARM64 or ARM architectures.? For example, rpi ?

### ISSUE THREAD

**Issue by daozhu** [pantsel/konga#457]
duo to kong now support the ARM64 architectures since version 1.3.0 , so i can run it on rpi, but the konga ,i built the docker images failed on rpi, the Raspbian system. so ...

**Comment by gorositopablo** [comment]
I got here looking for an image for konga ARM, and made my own image by changing the dockerfile.
You can find it here
hub.docker.com/r/gorositopablo/konga/

**Comment by daozhu** [comment]
@gorositopablo  i am trying , but got some errors 

```
2020-05-25T12:02:31.494554730Z Using postgres DB Adapter.
2020-05-25T12:02:31.578003620Z Database `konga01` does not exist. Creating...
2020-05-25T12:02:32.331021940Z Database `konga01` created! Continue...
2020-05-25T12:02:47.256659423Z error: A hook (`orm`) failed to load!
2020-05-25T12:02:47.272234254Z error: error: column r.consrc does not exist
2020-05-25T12:02:47.272366121Z     at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
2020-05-25T12:02:47.272403954Z     at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
2020-05-25T12:02:47.272448434Z     at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
2020-05-25T12:02:47.272472323Z     at emitOne (events.js:116:13)
2020-05-25T12:02:47.272511303Z     at Socket.emit (events.js:211:7)
2020-05-25T12:02:47.272535692Z     at addChunk (_stream_readable.js:263:12)
2020-05-25T12:02:47.272556858Z     at readableAddChunk (_stream_readable.js:250:11)
2020-05-25T12:02:47.272594857Z     at Socket.Readable.push (_stream_readable.js:208:10)
2020-05-25T12:02:47.272618412Z     at TCP.onread (net.js:601:20)
2020-05-25T12:02:47.277005971Z /app/node_modules/sails-postgresql/lib/adapter.js:158
2020-05-25T12:02:47.277089025Z         var collection = connectionObject.collections[table];
2020-05-25T12:02:47.277117024Z                                           ^
2020-05-25T12:02:47.277140172Z 
2020-05-25T12:02:47.277163301Z TypeError: Cannot read property 'collections' of undefined
2020-05-25T12:02:47.277187004Z     at __DESCRIBE__ (/app/node_modules/sails-postgresql/lib/adapter.js:158:43)
2020-05-25T12:02:47.277208448Z     at after (/app/node_modules/sails-postgresql/lib/adapter.js:1292:7)
2020-05-25T12:02:47.277229578Z     at /app/node_modules/sails-postgresql/lib/adapter.js:1181:7
2020-05-25T12:02:47.277250744Z     at /app/node_modules/sails-postgresql/node_modules/pg/lib/pool.js:84:11
2020-05-25T12:02:47.277271669Z     at dispense (/app/node_modules/sails-postgresql/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:250:16)
2020-05-25T12:02:47.277293187Z     at Object.me.release (/app/node_modules/sails-postgresql/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:349:5)
2020-05-25T12:02:47.277314631Z     at /app/node_modules/sails-postgresql/node_modules/pg/lib/pool.js:88:20
2020-05-25T12:02:47.277335242Z     at /app/node_modules/sails-postgresql/lib/adapter.js:1295:9
2020-05-25T12:02:47.277356149Z     at Query.callback (/app/node_modules/sails-postgresql/lib/adapter.js:195:26)
2020-05-25T12:02:47.277377426Z     at Query.handleError (/app/node_modules/sails-postgresql/node_modules/pg/lib/query.js:106:17)
2020-05-25T12:02:47.277398685Z     at Connection.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/client.js:171:26)
2020-05-25T12:02:47.277470924Z     at emitOne (events.js:116:13)
2020-05-25T12:02:47.277493202Z     at Connection.emit (events.js:211:7)
2020-05-25T12:02:47.277512738Z     at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:109:12)
2020-05-25T12:02:47.277534219Z     at emitOne (events.js:116:13)
2020-05-25T12:02:47.277553978Z     at Socket.emit (events.js:211:7)
2020-05-25T12:02:47.277573367Z     at addChunk (_stream_readable.js:263:12)
2020-05-25T12:02:47.277592589Z     at readableAddChunk (_stream_readable.js:250:11)
2020-05-25T12:02:47.277611866Z     at Socket.Readable.push (_stream_readable.js:208:10)
2020-05-25T12:02:47.277631255Z     at TCP.onread (net.js:601:20)
```

here is my code :
```
sudo docker run -d -p 1337:1337 \
             -e "TOKEN_SECRET=1234a_A" \
             -e "DB_ADAPTER=postgres" \
             -e "DB_HOST=192.168.23.4" \
             -e "DB_USER=kong" \
             -e "DB_PASSWORD=kong" \
	     -e "DB_DATABASE=konga01" \
             --name konga01 \
             gorositopablo/konga \
```

**Comment by gorositopablo** [comment]
I got the same error as well. Seems like the problem it's the postegresql version.
With the 9.6 version it works fine. 
https://github.com/pantsel/konga/issues/462

I am using on kube, so the helm deployment looks like this:
helm install --namespace kong --name konga-postgresql stable/postgresql \
   --set image.repository=arm64v8/postgres \
   --set image.tag=9.6 \
   --set replication.enabled=false \
   --set replication.slaveReplicas=1 \
   --set persistence.enabled=true \
   --set persistence.storageClass=local-path \
   --set postgresqlDataDir=/data/pgdata \
   --set persistence.mountPath=/data/ \
   --set postgresqlDatabase=konga \
   --set postgresqlUsername="yourusername" \
   --set postgresqlPassword="yourpassword"

**Comment by daozhu** [comment]
yes, i changed the postgres version to 9.6 , and it works fine

thanks @gorositopablo

**Comment by exqlnet** [comment]
i'm trying to build konga arm64. But it doesn't work while connecting to postgres without any error msg except one line.

```
Using postgres DB Adapter.
```

**Comment by akshaykrjain** [comment]
@gorositopablo Your image works for me. However, I need to build it for another version of Konga. Would you mind sharing your Dockerfile.

**Comment by marioluciano** [comment]
@gorositopablo I am trying to use your image, but I am facing some problems in loading resources, even using the `BASE_URL` env `/konga/`. Do you have any tip about this?
