### ISSUE TITLE
konga not works "error: A hook (`orm`) failed to load"

### ISSUE THREAD

**Issue by xpoveda** [pantsel/konga#462]
Hi, somedays ago konga is installed perfect but now returns this error always (swarm and not swarm mode)

```sh
ubuntu@pre@:~/misproyectos/entorno-ci-herramientas/src/aws/kong(master)$ docker run -p 1337:1337 --network demo_net -e "DB_ADAPTER=postgres" -e "DB_HOST=postgresdemo" -e "DB_PORT=5432" -e "DB_USER=kong" -e "DB_PASSWORD=kong" -e "DB_DATABASE=kong" --name konga pantsel/konga
Using postgres DB Adapter.
Database exists. Continue...
error: A hook (`orm`) failed to load!
error: error: column r.consrc does not exist
    at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
/app/node_modules/sails-postgresql/lib/adapter.js:158
        var collection = connectionObject.collections[table];
                                          ^

TypeError: Cannot read property 'collections' of undefined
    at __DESCRIBE__ (/app/node_modules/sails-postgresql/lib/adapter.js:158:43)
    at after (/app/node_modules/sails-postgresql/lib/adapter.js:1292:7)
    at /app/node_modules/sails-postgresql/lib/adapter.js:1181:7
    at /app/node_modules/sails-postgresql/node_modules/pg/lib/pool.js:84:11
    at dispense (/app/node_modules/sails-postgresql/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:250:16)
    at Object.me.release (/app/node_modules/sails-postgresql/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:349:5)
    at /app/node_modules/sails-postgresql/node_modules/pg/lib/pool.js:88:20
    at /app/node_modules/sails-postgresql/lib/adapter.js:1295:9
    at Query.callback (/app/node_modules/sails-postgresql/lib/adapter.js:195:26)
    at Query.handleError (/app/node_modules/sails-postgresql/node_modules/pg/lib/query.js:106:17)
    at Connection.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/client.js:171:26)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
```

Thanks so much in advance.

Kind regards!!

Xavier.

**Comment by xpoveda** [comment]
Hi everybody, 

I have added the KONGA_HOOK_TIMEOUT environment variable but not works...;__(

```version: '3.0'

services:

  konga:
    image: pantsel/konga
    networks:
      - demo_net
    ports:
      - 80:1337
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=postgresdemo
      - DB_USER=kong
      - DB_PASSWORD=kong
      - DB_DATABASE=kong
      - NODE_ENV=development
      - KONGA_HOOK_TIMEOUT=120000
    deploy:
      replicas: 1

networks:
  demo_net:
    external: true
```

**Comment by lukasa1993** [comment]
i am having this issue with postgres 12  its simply not supported?

**Comment by xpoveda** [comment]
Hi,when I have this issue simply is this, with postgres 9.6 works perfect.

Xavier.

**Comment by lukasa1993** [comment]
i really need this to work on postgres12 :( @pantsel any idea how i can make it ?

**Comment by pantsel** [comment]
@lukasa1993 , unfortunatelly pg 12 is not supported by the underlying driver. It all comes down to the sails framework used by Konga. An update to the most recent version requires a whole rewrite of the project. On the upside, a second generation of Konga is in the works but it will take some time for it to be publicly available.

If you have no alternatives, I would suggest that you use the build-in filesystem db, provided that you can mount a volume to `konga-data` folder. I've done it with no problems on production environments.

**Comment by lukasa1993** [comment]
filesystem-db works in production mode ?  and what would be docker mount point for it ?

**Comment by pantsel** [comment]
If I understand you question correctly it would be something in the line of `/host/path:/konga-data`

**Comment by lukasa1993** [comment]
so it works in production mode… what is latest version of postgres that it works ?

**Comment by pantsel** [comment]
Yes, it works in production. I think 9.6, the adapter is quite old.

**Comment by lukasa1993** [comment]
`/app/kongadata` isn't this path for docker container ? /konga-data is empty…

**Comment by pantsel** [comment]
Yup, sorry.

**Comment by lukasa1993** [comment]
ty, looking forward new konga hit me up for testing when its ready

**Comment by pantsel** [comment]
Ofcourse, there will also be an announcement on gitter

**Comment by Carmezim** [comment]
Could be helpful adding a note regarding Postgres 12+ incompatibility to the docs, thanks for the clarification though.

**Comment by ttpro1995** [comment]
confirm Postgres 13 also have this error

```
sudo docker run --rm pantsel/konga:latest -c prepare -a postgres -u postgresql://konga:meowmeowmeow@my_ip:5432/konga
debug: Preparing database...
Using postgres DB Adapter.
Database exists. Continue...
error: A hook (`orm`) failed to load!
error: Failed to prepare database: error: column r.consrc does not exist
    at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by sudhanshud** [comment]
I am facing the same issue when using mongo Atlas. Any idea?

**Comment by RagunathInGIT** [comment]
@pantsel - Do we have the latest version of Konga that connects to postgres 12 or later?

**Comment by tianqing108** [comment]
@pantsel this issue was happened one years age,why don't you fix it?  up you lib ,it may be works

**Comment by bangdoni** [comment]
I tried on Postgresql 9.6 -> [link](https://www.rosehosting.com/blog/how-to-install-postgresql-9-6-on-ubuntu-20-04/)
and .env file

```
PORT=1337
NODE_ENV=production
KONGA_HOOK_TIMEOUT=120000
DB_ADAPTER=postgres
DB_URI=postgresql://dbuser:dbpassword@localhost:5432/kongadb
DB_USER=dbuser
DB_PORT=5432
DB_DATABASE=kongadb
DB_PASSWORD=dbpassword
KONGA_LOG_LEVEL=warn
TOKEN_SECRET=your-token
```

**Comment by lpj145** [comment]
https://github.com/balderdashy/sails/issues/6957 issue is with sailsjs and the solution to the creator are here: https://github.com/balderdashy/sails/issues/6957#issuecomment-591954307

**Comment by isaac88** [comment]
For those that they have the possibility to use MySQL,
I've tested with the latest"current" version 8.0.29 and it works fine.

**Comment by gharia** [comment]
> @lukasa1993 , unfortunatelly pg 12 is not supported by the underlying driver. It all comes down to the sails framework used by Konga. An update to the most recent version requires a whole rewrite of the project. On the upside, a second generation of Konga is in the works but it will take some time for it to be publicly available.
> 
> If you have no alternatives, I would suggest that you use the build-in filesystem db, provided that you can mount a volume to `konga-data` folder. I've done it with no problems on production environments.

@pantsel, any update of supporting the latest postgres or any plan in the near future?

**Comment by gbl-michell** [comment]
:eyes:

**Comment by salao-na-mao** [comment]
> I am facing the same issue when using mongo Atlas. Any idea?

Same here :/

**Comment by sudhanshud** [comment]
Hi,

R u using normal connection string or mongo srv connection string?

Thanks,
Sudhanshu Dev

**Comment by mhagou** [comment]
Hi,

take a look on this https://github.com/pantsel/konga/issues/487.

I describe a solution for postgres 14.

Regards.
