### ISSUE TITLE
Cannot create a connection to kong

### ISSUE THREAD

**Issue by luka29** [pantsel/konga#471]
Unable to create a connection to kong.
*user has all permissions enabled

`kong-database_1   | STATEMENT:  INSERT INTO "public"."konga_kong_nodes" ("type", "jwt_algorithm", "kong_admin_url", "name", "kong_api_key", "kong_version", "health_checks", "active", "createdAt", "updatedAt", "createdUserId", "updatedUserId") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING *
konga_1           | Sending 500 ("Server Error") response:
konga_1           |  Error (E_UNKNOWN) :: Encountered an unexpected error
konga_1           | error: invalid input syntax for integer: "NaN"
konga_1           |     at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
konga_1           |     at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
konga_1           |     at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
konga_1           |     at Socket.emit (events.js:198:13)
konga_1           |     at Socket.EventEmitter.emit (domain.js:448:20)
konga_1           |     at addChunk (_stream_readable.js:288:12)
konga_1           |     at readableAddChunk (_stream_readable.js:269:11)
konga_1           |     at Socket.Readable.push (_stream_readable.js:224:10)
konga_1           |     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
konga_1           |
konga_1           | Details:  error: invalid input syntax for integer: "NaN"
konga_1           |
`

In the network tab it shows:
`
{"originalError":{"name":"error","length":92,"severity":"ERROR","code":"22P02","file":"numutils.c","line":"62","routine":"pg_atoi"},"_e":{"name":"error","length":92,"severity":"ERROR","code":"22P02","file":"numutils.c","line":"62","routine":"pg_atoi"},"rawStack":"error: invalid input syntax for integer: \"NaN\"\n    at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)\n    at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)\n    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)\n    at Socket.emit (events.js:198:13)\n    at Socket.EventEmitter.emit (domain.js:448:20)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","details":"Details:  error: invalid input syntax for integer: \"NaN\"\n","message":"[Error (E_UNKNOWN) Encountered an unexpected error] Details:  error: invalid input syntax for integer: \"NaN\"\n","stack":"Error (E_UNKNOWN) :: Encountered an unexpected error\nerror: invalid input syntax for integer: \"NaN\"\n    at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)\n    at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)\n    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)\n    at Socket.emit (events.js:198:13)\n    at Socket.EventEmitter.emit (domain.js:448:20)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)"}
`

**Comment by LKI** [comment]
maybe duplicate to #474
