### ISSUE TITLE
Can't add/edit key name for key-auth plugin

### ISSUE THREAD

**Issue by zeldi** [pantsel/konga#48]
Hi Konga Team,

When adding/editing Key-Auth plugin, I can't specify the key-name.
The specified the key-name remains empty.  

But I can successfully add the key name if I use kong API (command line via curl)

Hope you can fix the bug

Thanks

**Comment by pantsel** [comment]
Hello @zeldi,
Check out issue #9, you just need to press enter after every key you write so that the chip component takes it. This will be better commented.

Thanks for the feedback!

**Comment by zeldi** [comment]
Hi Pantsel,

Thanks for your prompt response, you right I just need to press enter.
Yes. It would be helpful if you put a comment (to press enter) below the input box

Thanks again

**Comment by chengyuk** [comment]
[root@kong ~]# docker run --rm  --network=kong-net  pantsel/konga:latest -c prepare -a postgres -u postgres://konga@konga-database:5432/konga
debug: Preparing database...
Using postgres DB Adapter.
Failed to connect to DB { error: password authentication failed for user "konga"
    at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'error',
  length: 101,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '307',
  routine: 'auth_failed' }
