### ISSUE TITLE
 error: no PostgreSQL user name specified in startup packet

### ISSUE THREAD

**Issue by lzp9421** [pantsel/konga#481]
error: no PostgreSQL user name specified in startup packet

**Comment by rawc0der** [comment]
Hi, this issue happens when enabling the Postgres DB Adapter using this image _bitnami/postgresql:11.3.0-debian-9-r17_

Error:
`Using postgres DB Adapter.
Failed to connect to DB { error: no PostgreSQL user name specified in startup packet
    at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
  name: 'error',
...
`
Possibly there are some environment variables not mapped out correctly. Any advice?

**Comment by g-kawin** [comment]
any update?
