### ISSUE TITLE
Cannot Run in Production Env

### ISSUE THREAD

**Issue by erwinyusrizal** [pantsel/konga#482]
Hi I tried to run Konga in production env, when I run migration 

`$ node ./bin/konga.js  prepare --adapter postgres --uri postgresql://username:password@localhost:5432/konga`

I got this error

```
error: A hook (`helpers`) failed to load!
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
error: Failed to prepare database: ImplementationError: Failed to load helper `utils` into a Callable!  Sorry, could not interpret "utils" because its underlying implementation has a problem:
------------------------------------------------------
• Missing the `fn` property.
------------------------------------------------------

If you are the maintainer of "utils", then you can change its implementation to solve the problem above.  Otherwise, please file a bug report with the maintainer, or fork your own copy and fix that.
 [?] See https://sailsjs.com/support for help.
    at flaverr (/home/cumba/web/konga/node_modules/flaverr/index.js:94:15)
    at helpBuildMachine (/home/cumba/web/konga/node_modules/machine/lib/private/help-build-machine.js:178:11)
    at Function.buildWithCustomUsage (/home/cumba/web/konga/node_modules/machine/lib/build-with-custom-usage.js:38:10)
    at Hook.furnishHelper (/home/cumba/web/konga/node_modules/sails/lib/hooks/helpers/index.js:411:68)
    at Hook.wrapper [as furnishHelper] (/home/cumba/web/konga/node_modules/@sailshq/lodash/lib/index.js:3282:19)
    at /home/cumba/web/konga/node_modules/sails/lib/hooks/helpers/private/load-helpers.js:94:31
    at /home/cumba/web/konga/node_modules/@sailshq/lodash/lib/index.js:3260:15
    at baseForOwn (/home/cumba/web/konga/node_modules/@sailshq/lodash/lib/index.js:2230:14)
    at /home/cumba/web/konga/node_modules/@sailshq/lodash/lib/index.js:3230:18
    at Function.<anonymous> (/home/cumba/web/konga/node_modules/@sailshq/lodash/lib/index.js:3533:13)
    at /home/cumba/web/konga/node_modules/sails/lib/hooks/helpers/private/load-helpers.js:42:9
    at helpBuildDictionary (/home/cumba/web/konga/node_modules/include-all/lib/help-build-dictionary.js:135:10)
    at Function.module.exports.optional (/home/cumba/web/konga/node_modules/include-all/index.js:67:10)
    at loadHelpers (/home/cumba/web/konga/node_modules/sails/lib/hooks/helpers/private/load-helpers.js:24:14)
    at Hook.initialize (/home/cumba/web/konga/node_modules/sails/lib/hooks/helpers/index.js:285:7)
    at Hook.wrapper [as initialize] (/home/cumba/web/konga/node_modules/@sailshq/lodash/lib/index.js:3282:19)
    at /home/cumba/web/konga/node_modules/sails/lib/hooks/index.js:122:20
    at /home/cumba/web/konga/node_modules/sails/node_modules/async/dist/async.js:421:16
    at processQueue (/home/cumba/web/konga/node_modules/sails/node_modules/async/dist/async.js:1565:20)
    at taskComplete (/home/cumba/web/konga/node_modules/sails/node_modules/async/dist/async.js:1588:9)
    at /home/cumba/web/konga/node_modules/sails/node_modules/async/dist/async.js:1612:17
    at /home/cumba/web/konga/node_modules/sails/node_modules/async/dist/async.js:906:16
```

any idea how to fix it?

Thank you

**Comment by erwinyusrizal** [comment]
I tried to run development mode, I got the other error 

```
$ npm start

> kongadmin@0.14.7 start /home/cumba/web/konga
> node --harmony app.js

internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '../../node_modules/sails-postgresql/node_modules/pg'
Require stack:
- /home/cumba/web/konga/makedb/dbs/pg.js
- /home/cumba/web/konga/makedb/index.js
- /home/cumba/web/konga/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/cumba/web/konga/makedb/dbs/pg.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at module.exports (/home/cumba/web/konga/makedb/index.js:13:20)
    at Object.<anonymous> (/home/cumba/web/konga/app.js:66:20)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/cumba/web/konga/makedb/dbs/pg.js',
    '/home/cumba/web/konga/makedb/index.js',
    '/home/cumba/web/konga/app.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kongadmin@0.14.7 start: `node --harmony app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kongadmin@0.14.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/setali/.npm/_logs/2019-10-25T16_38_17_842Z-debug.log
```

**Comment by erwinyusrizal** [comment]
Ok solved it, the problem was node-sass doesnt support with node version 12.x

so I downgrade my nodejs version to version 10.x
