### ISSUE TITLE
Lets make sure that it is working first.

### ISSUE THREAD

**Issue by dplbiz** [pantsel/konga#495]
Lets make sure that it is working first.
For now, don't change anything.

Is it working if you follow the steps I mentioned above?

_Originally posted by @pantsel in https://github.com/pantsel/konga/issues/354#issuecomment-473180563_

I follow your step and get these errors
../../nan/nan.h:2337:3: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>&, v8::Local<v8::Function>)’
   recv->Set(name, GetFunction(tpl).ToLocalChecked());
   ^
In file included from /home/ubuntu/.node-gyp/13.0.1/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/binding.cpp:1:
/home/ubuntu/.node-gyp/13.0.1/include/node/v8.h:3416:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^
/home/ubuntu/.node-gyp/13.0.1/include/node/v8.h:3416:37: note:   candidate expects 3 arguments, 2 provided
/home/ubuntu/.node-gyp/13.0.1/include/node/v8.h:3419:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^
/home/ubuntu/.node-gyp/13.0.1/include/node/v8.h:3419:37: note:   candidate expects 3 arguments, 2 provided
binding.target.mk:129: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/ubuntu/homecca/konga/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/homecca/konga/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.4.0-1092-aws
gyp ERR! command "/usr/bin/node" "/home/ubuntu/homecca/konga/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/ubuntu/homecca/konga/node_modules/node-sass
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-11-16T02_04_04_828Z-debug.log

**Comment by infoloft** [comment]
Try nodejs max version 10.x,x
