### ISSUE TITLE
Internal Server Error - Services and Routes

### ISSUE THREAD

**Issue by JuniorCtba** [pantsel/konga#498]
Hello,

I am using the latest version and i am getting in most of times HTTP error 500, for service and routes.

The version of kong is 1.3.0

![image](https://user-images.githubusercontent.com/13451867/69174171-0b7e4c80-0ae0-11ea-839d-04eb5a891d7d.png)

In the server the log of error is not so good also.

toJSON: [Function: responseToJSON],
--
  | caseless:
  | Caseless {
  | dict:
  | { date: 'Tue, 19 Nov 2019 18:17:41 GMT',
  | 'content-type': 'application/json; charset=utf-8',
  | connection: 'close',
  | 'access-control-allow-origin': '*',
  | server: 'kong/1.3.0',
  | 'content-length': '42' } },
  | read: [Function],
  | body: { message: 'An unexpected error occurred' },
  | code: 500,
  | status: 500,
  | statusType: 5,
  | info: false,
  | ok: false,
  | clientError: false,
  | serverError: true,
  | error: { Error: got 500 response
  | at generateErrorMessage (/app/node_modules/unirest/index.js:470:23)
  | at Request.handleRequestResponse [as _callback] (/app/node_modules/unirest/index.js:473:13)
  | at Request.self.callback (/app/node_modules/unirest/node_modules/request/request.js:185:22)
  | at emitTwo (events.js:126:13)
  | at Request.emit (events.js:214:7)
  | at Request.<anonymous> (/app/node_modules/unirest/node_modules/request/request.js:1161:10)
  | at emitOne (events.js:116:13)
  | at Request.emit (events.js:211:7)
  | at IncomingMessage.<anonymous> (/app/node_modules/unirest/node_modules/request/request.js:1083:12)
  | at Object.onceWrapper (events.js:313:30)
  | at emitNone (events.js:111:20)
  | at IncomingMessage.emit (events.js:208:7)
  | at endReadableNT (_stream_readable.js:1064:12)
  | at _combinedTickCallback (internal/process/next_tick.js:139:11)
  | at process._tickDomainCallback (internal/process/next_tick.js:219:9) status: 500 },

**Comment by JuniorCtba** [comment]
For update some of the services, i am also getting the same error
![image](https://user-images.githubusercontent.com/13451867/69175413-7cbeff00-0ae2-11ea-8a46-ef4f9ba57de3.png)
![image](https://user-images.githubusercontent.com/13451867/69175505-aaa44380-0ae2-11ea-90d4-bbc3ba47ac42.png)

**Comment by uvv17** [comment]
I am also getting the same issue while creating a new service. Any solution to this problem?
