### ISSUE TITLE
fail to connect postgresql-11

### ISSUE THREAD

**Issue by vsuns** [pantsel/konga#510]
Hello , my docker command like :
`docker run --rm pantsel/konga:latest -c prepare -a postgres -u postgresql://kongs:kong# @192.168.56.106:5432/kongs
` 
and it shows :
debug: Preparing database...
Using postgres DB Adapter.
Failed to connect to DB { Error: getaddrinfo EAI_AGAIN kongs kongs:5432
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'kongs',
  host: 'kongs',
  port: 5432 }

----------------
it looks like password with "#"  cause failed !
any advice?

**Comment by bkumar0801** [comment]
use "%23" instead of "#" in password. "%23" is "#" equivalent can be used in password

**Comment by KeithTt** [comment]
meet the same error, there is no password to my postgres.

```
# docker run --rm pantsel/konga:latest -c prepare -a postgres -u postgresql://localhost:5432/konga
debug: Preparing database...
Using postgres DB Adapter.
Failed to connect to DB Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
```

How to pass the DB_URL?
