### ISSUE TITLE
Uglify hanging the app to start 

### ISSUE THREAD

**Issue by Xplouder** [pantsel/konga#538]
Greetings, for some reason the uglify step is hanging the app to start...here are the complete logs with verbosity as `KONGA_LOG_LEVEL=silly`:

```
Attaching to api-gateway_konga_1
konga_1  | 2020-03-03T03:19:20.928384703Z logger hook loaded successfully.
konga_1  | 2020-03-03T03:19:20.928442326Z request hook loaded successfully.
konga_1  | 2020-03-03T03:19:20.928448263Z Loading the app's models and any custom adapters...
konga_1  | 2020-03-03T03:19:20.928452489Z Loading app models...
konga_1  | 2020-03-03T03:19:20.948159783Z Loading app adapters...
konga_1  | 2020-03-03T03:19:20.951776494Z Overriding ejs engine config with ejslocals to implement layout support...
konga_1  | 2020-03-03T03:19:20.953848502Z views hook loaded successfully.
konga_1  | 2020-03-03T03:19:20.953868217Z Loading blueprint middleware...
konga_1  | 2020-03-03T03:19:20.953871665Z blueprints hook loaded successfully.
konga_1  | 2020-03-03T03:19:20.953874737Z responses hook loaded successfully.
konga_1  | 2020-03-03T03:19:20.975855341Z controllers hook loaded successfully.
konga_1  | 2020-03-03T03:19:20.978360413Z Loading policy modules from app...
konga_1  | 2020-03-03T03:19:20.985567007Z Finished loading policy middleware logic.
konga_1  | 2020-03-03T03:19:20.985590245Z policies hook loaded successfully.
konga_1  | 2020-03-03T03:19:20.985593436Z services hook loaded successfully.
konga_1  | 2020-03-03T03:19:20.985605064Z csrf hook loaded successfully.
konga_1  | 2020-03-03T03:19:20.985607983Z cors hook loaded successfully.
konga_1  | 2020-03-03T03:19:21.004403135Z i18n hook loaded successfully.
konga_1  | 2020-03-03T03:19:21.004447013Z Loading app Gruntfile...
konga_1  | 2020-03-03T03:19:21.023788856Z Tracking new grunt child process...
konga_1  | 2020-03-03T03:19:21.037791919Z Setting default Express view engine to ejs...
konga_1  | 2020-03-03T03:19:21.385307554Z http hook loaded successfully.
konga_1  | 2020-03-03T03:19:21.385342458Z Preparing socket.io...
konga_1  | 2020-03-03T03:19:21.416421484Z sockets hook loaded successfully.
konga_1  | 2020-03-03T03:19:21.422078310Z Loading adapter (`sails-postgresql`) from this app's `node_modules/` directory...
konga_1  | 2020-03-03T03:19:21.724873979Z For `apihealthcheck` model, forcing Waterline to use `migrate: "safe" strategy (since this is production)
konga_1  | 2020-03-03T03:19:21.724917443Z For `emailtransport` model, forcing Waterline to use `migrate: "safe" strategy (since this is production)
konga_1  | 2020-03-03T03:19:21.724925977Z For `kongnode` model, forcing Waterline to use `migrate: "safe" strategy (since this is production)
konga_1  | 2020-03-03T03:19:21.738879349Z For `kongservices` model, forcing Waterline to use `migrate: "safe" strategy (since this is production)
konga_1  | 2020-03-03T03:19:21.738915830Z For `netdataconnection` model, forcing Waterline to use `migrate: "safe" strategy (since this is production)
konga_1  | 2020-03-03T03:19:21.738921359Z For `passport` model, forcing Waterline to use `migrate: "safe" strategy (since this is production)
konga_1  | 2020-03-03T03:19:21.738925824Z For `settings` model, forcing Waterline to use `migrate: "safe" strategy (since this is production)
konga_1  | 2020-03-03T03:19:21.738930222Z For `snapshot` model, forcing Waterline to use `migrate: "safe" strategy (since this is production)
konga_1  | 2020-03-03T03:19:21.738934511Z For `snapshotschedule` model, forcing Waterline to use `migrate: "safe" strategy (since this is production)
konga_1  | 2020-03-03T03:19:21.738951218Z For `upstreamalert` model, forcing Waterline to use `migrate: "safe" strategy (since this is production)
konga_1  | 2020-03-03T03:19:21.738956052Z For `user` model, forcing Waterline to use `migrate: "safe" strategy (since this is production)
konga_1  | 2020-03-03T03:19:21.738960417Z Starting ORM...
konga_1  | 2020-03-03T03:19:21.738964550Z Registering model `apihealthcheck` in Waterline (ORM)
konga_1  | 2020-03-03T03:19:21.750782327Z Registering model `emailtransport` in Waterline (ORM)
konga_1  | 2020-03-03T03:19:21.750825621Z Registering model `kongnode` in Waterline (ORM)
konga_1  | 2020-03-03T03:19:21.750831931Z Registering model `kongservices` in Waterline (ORM)
konga_1  | 2020-03-03T03:19:21.750836122Z Registering model `netdataconnection` in Waterline (ORM)
konga_1  | 2020-03-03T03:19:21.750841196Z Registering model `passport` in Waterline (ORM)
konga_1  | 2020-03-03T03:19:21.750844872Z Registering model `settings` in Waterline (ORM)
konga_1  | 2020-03-03T03:19:21.750848608Z Registering model `snapshot` in Waterline (ORM)
konga_1  | 2020-03-03T03:19:21.750852223Z Registering model `snapshotschedule` in Waterline (ORM)
konga_1  | 2020-03-03T03:19:21.750856329Z Registering model `upstreamalert` in Waterline (ORM)
konga_1  | 2020-03-03T03:19:21.750860321Z Registering model `user` in Waterline (ORM)
konga_1  | 2020-03-03T03:19:22.376617449Z orm hook loaded successfully.
konga_1  | 2020-03-03T03:19:22.514380748Z pubsub hook loaded successfully.
konga_1  | 2020-03-03T03:19:25.163343651Z Hook:api_health_checks:process() called
konga_1  | 2020-03-03T03:19:31.728277838Z api-health-checks hook loaded successfully.
konga_1  | 2020-03-03T03:19:36.247688155Z node-health-checks hook loaded successfully.
konga_1  | 2020-03-03T03:19:31.894577963Z Hook:health_checks:process() called
konga_1  | 2020-03-03T03:19:40.879985820Z start-scheduled-snapshots hook loaded successfully.
konga_1  | 2020-03-03T03:19:50.160943162Z upstream-health-checks hook loaded successfully.
konga_1  | 2020-03-03T03:19:47.003746620Z Hook:start-scheduled-snapshots:process() called
konga_1  | 2020-03-03T03:19:51.232374700Z user-events-hook hook loaded successfully.
konga_1  | 2020-03-03T03:19:54.171364803Z Hook:upstream_health_checks:process() called
konga_1  | 2020-03-03T03:19:57.430725873Z Hook:user_events_hook:process() called
konga_1  | 2020-03-03T03:20:26.714962212Z User had models, so no seed needed
konga_1  | 2020-03-03T03:20:30.384639029Z Kongnode had models, so no seed needed
konga_1  | 2020-03-03T03:20:30.681010849Z Emailtransport seeds updated
konga_1  | 2020-03-03T03:20:30.768066155Z load-db hook loaded successfully.
konga_1  | 2020-03-03T03:20:32.077065133Z Grunt :: Running "clean:dev" (clean) task
konga_1  | 2020-03-03T03:20:32.077113977Z Grunt :: >> 0 paths cleaned.
konga_1  | 2020-03-03T03:20:32.077120967Z Grunt :: Running "jst:dev" (jst) task
konga_1  | 2020-03-03T03:20:32.082699913Z Grunt :: >> Destination not written because compiled files were empty.
konga_1  | 2020-03-03T03:20:32.082737616Z 
konga_1  | 2020-03-03T03:20:32.082741978Z Running "less:dev" (less) task
konga_1  | 2020-03-03T03:20:32.104608730Z Grunt :: Running "sass:dev" (sass) task
konga_1  | 2020-03-03T03:20:32.405660978Z Grunt :: Running "copy:dev" (copy) task
konga_1  | 2020-03-03T03:20:36.926332732Z Grunt :: Created 16 directories, copied 1928 files
konga_1  | 2020-03-03T03:20:36.957173186Z Grunt :: Running "concat:js" (concat) task
konga_1  | 2020-03-03T03:20:37.173408928Z Grunt :: Running "concat:css" (concat) task
konga_1  | 2020-03-03T03:20:37.197456032Z Grunt :: Running "uglify:dist" (uglify) task
konga_1  | 2020-03-03T04:59:20.955633214Z Lowering sails...
konga_1  | 2020-03-03T04:59:20.959180573Z Sent kill signal to child process (17)...
konga_1  | 2020-03-03T04:59:20.973965766Z Shutting down HTTP server...
konga_1  | 2020-03-03T04:59:20.978300158Z HTTP server shut down successfully.
konga_1  | 2020-03-03T04:59:20.987180575Z Error: The hook `grunt` is taking too long to load.
konga_1  | 2020-03-03T04:59:20.987230053Z Make sure it is triggering its `initialize()` callback, or else set `sails.config.grunt._hookTimeout to a higher value (currently 6000000)
konga_1  | 2020-03-03T04:59:20.987241568Z     at Timeout.tooLong [as _onTimeout] (/app/node_modules/sails/lib/app/private/loadHooks.js:85:21)
konga_1  | 2020-03-03T04:59:20.987250573Z     at ontimeout (timers.js:436:11)
konga_1  | 2020-03-03T04:59:20.987258770Z     at tryOnTimeout (timers.js:300:5)
konga_1  | 2020-03-03T04:59:20.987267399Z     at listOnTimeout (timers.js:263:5)
konga_1  | 2020-03-03T04:59:20.987275419Z     at Timer.processTimers (timers.js:223:10)
```

konga_1  | 2020-03-03T**03:20:37.197456032Z** Grunt :: Running "uglify:dist" (uglify) task
konga_1  | 2020-03-03T**04:59:20.955633214Z** Lowering sails...

The startup fails about after 1h and 30min! I used `KONGA_HOOK_TIMEOUT=6000000` on purpose to see if using a huge number the problem would still occur.

Any thoughts?

**Comment by stpice** [comment]
i have the same problem, can someone help me?
