### ISSUE TITLE
DB_HOST get wrong if DB_PORT is not 3306 and DB_ADAPTER is mysql

### ISSUE THREAD

**Issue by aloisio31** [pantsel/konga#539]
If I set the DB_URI `mysql://user:passwd@10.226.196.7:3306/konga`, it works ok.
If I set the DB_URI `mysql://user:passwd@10.226.196.7:3358/konga`, it will try `mysql://user:passwd@10.226.209.102:3306/konga`.
And the IP `10.226.209.102` is the konga container IP which is set by macvlan plugin.

Here is my docker logs:
```
# docker logs 1b
Using MySQL DB Adapter.
Creating database `konga` if not exists.
(node:6) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
{ Error: ER_DBACCESS_DENIED_ERROR: Access denied for user 'user'@'10.226.209.102' to database 'konga'
    at Query.Sequence._packetToError (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/app/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    --------------------
    at Protocol._enqueue (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/app/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:201:25)
    at Object.create (/app/makedb/dbs/mysql.js:51:16)
    at Object.run (/app/makedb/dbs/mysql.js:29:17)
    at module.exports (/app/makedb/index.js:15:43)
    at Object.<anonymous> (/app/app.js:66:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
  code: 'ER_DBACCESS_DENIED_ERROR',
  errno: 1044,
  sqlState: '42000',
  index: 0 }
```

**Comment by marciodiasdeveloper** [comment]
+1
