### ISSUE TITLE
postgres12 compatible

### ISSUE THREAD

**Issue by shangxinbo** [pantsel/konga#545]
docker image  pantsel/konga:latest
[root@localhost /]# docker run --rm --network=kong-net pantsel/konga:latest -c prepare -a postgres -u postgresql://kong:123123@postgres:5432/konga
debug: Preparing database...
Using postgres DB Adapter.
Database `konga` does not exist. Creating...
Database `konga` created! Continue...
error: A hook (`orm`) failed to load!
error: Failed to prepare database: error: column r.consrc does not exist
    at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by larsnaesbye** [comment]
It is a part of Sails that uses this call now removed in Postgres12: https://github.com/balderdashy/sails/issues/6957

Maybe updating Sails could fix this.

**Comment by madisonhicks** [comment]
Hi, @shangxinbo! We'd love to know what version of Sails and Sails PostgreSQL you're using. Even more helpful would be a minimal repo that reproduces this behavior 😊 

Thanks for linking that issue, @larsnaesbye!

**Comment by mlehner616** [comment]
@pantsel Could we get this reopened and prioritized? Older PG versions are approaching EOL and this issue will be a dealbreaker in the near future.
