### ISSUE TITLE
error using SSL certs

### ISSUE THREAD

**Issue by DewangS** [pantsel/konga#554]
Konga throws below error when you configure cert and key in .env file and try to start Konga

 npm start

> kongadmin@0.14.7 start /opt/konga
> node --harmony app.js

Using postgres DB Adapter.
Database exists. Continue...
error: A hook (`http`) failed to load!
error: Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Object.createSecureContext (_tls_common.js:156:17)
    at Server (_tls_wrap.js:873:27)
    at new Server (https.js:62:14)
    at createServer (https.js:85:10)
    at _afterLoadingSessionHookIfApplicable (/opt/konga/node_modules/sails/lib/hooks/http/initialize.js:87:28)
    at _waitForSessionHookIfApplicable (/opt/konga/node_modules/sails/lib/hooks/http/initialize.js:40:16)
    at Hook.initialize (/opt/konga/node_modules/sails/lib/hooks/http/initialize.js:42:7)
    at Hook.wrapper [as initialize] (/opt/konga/node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at /opt/konga/node_modules/sails/lib/hooks/index.js:88:16
    at /opt/konga/node_modules/async/lib/async.js:52:16
    at /opt/konga/node_modules/async/lib/async.js:548:17
    at /opt/konga/node_modules/async/lib/async.js:542:17
    at _arrayEach (/opt/konga/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/opt/konga/node_modules/async/lib/async.js:541:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
error: A hook (`orm`) failed to load!

**Comment by pantsel** [comment]
@DewangS , how exactly have you configured them? Are they in PEM format?
