### ISSUE TITLE
is taking too long to load

### ISSUE THREAD

**Issue by zxlxiaoyi** [pantsel/konga#580]
**Execute "node. / bin"/ konga.js prepare --adapter postgres --uri p ostgresql://localhost : 5432 / Kong "why did the following error occur**

`[root@hecs-x-xlarge-2-linux-20200604174817 konga]# npm  start

> kongadmin@0.14.9 start /home/konga
> node --harmony app.js

(node:9614) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Error: The hook `api-health-checks` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.api-health-checks._hookTimeout to a higher value (currently 120000)
    at Timeout.tooLong [as _onTimeout] (/home/konga/node_modules/sails/lib/app/private/loadHooks.js:85:21)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
`

**Comment by deadlocks** [comment]
@zxlxiaoyi - I am also facing same issue, have you found any workaround?

**Comment by deadlocks** [comment]
In case anyone else is facing same issue
I switched to node 12.14.1 and it's working now.
