### ISSUE TITLE
Failed to authenticate user against LDAP

### ISSUE THREAD

**Issue by mdostal-hci** [pantsel/konga#584]
Hello,

I am using latest stable version of Konga with PostgreSQL as datastore. I have setup Konga to authenticate against LDAP provided by my company. When I try to login, authentication succeeds (I can see it in the logs of LDAP, and also user is created with proper attribute values in Konga's PostgreSQL database), but authentication fails with 401. I can see following error in the logs of Konga:

```verbose: User authentication failed
verbose: Error: Failed to serialize user into session
    at pass (/app/node_modules/passport/lib/authenticator.js:271:19)
    at serialized (/app/node_modules/passport/lib/authenticator.js:276:7)
    at serializeUser (/app/api/services/Passport.js:316:5)
    at pass (/app/node_modules/passport/lib/authenticator.js:284:9)
    at Authenticator.serializeUser (/app/node_modules/passport/lib/authenticator.js:289:5)
    at Authenticator.wrapper [as serializeUser] (/app/node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at IncomingMessage.req.login.req.logIn (/app/node_modules/passport/lib/http/request.js:48:29)
    at callback (/app/api/controllers/AuthController.js:281:15)
    at /app/api/services/protocols/ldap.js:41:17
...
```

I tried to add debug output at Passport.serializeUser, and the user object passed to the method does not contain "id" attribute. My guess is that the autogenerated user.id value does not propagate from PostgreSQL after user is inserted at first authentication success, but my knowledge of Sails is very limited so I might be wrong here.

**Comment by mdostal-hci** [comment]
I tried the same with DB_ADAPTER=localDisk and got the same result. Perhaps I am missing something here?

**Comment by mdostal-hci** [comment]
Actually I was able to resolve the issue myself at the end. It was combination of two issues - on first login, user was created in datastore but ID was not passed to next() calls; I fixed this and created a [pull request](https://github.com/pantsel/konga/pull/585).

Second issue was in LDAP attributes -> user mapping. Although I specified:

`KONGA_LDAP_ATTR_USERNAME=cn`

this is not honored in `ldap.getResolver` function; existing user can only be looked up based on "uid" or "sAMAccountName" attributes. I solved this by adding "sAMAccountName" to KONGA_LDAP_USER_ATTRS env variable, although it probably should be fixed directly in ldap.js.
