### ISSUE TITLE
konga fail to start in production mode with pgsql

### ISSUE THREAD

**Issue by sandeepgaana** [pantsel/konga#615]
error: A hook (`helpers`) failed to load!
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
error: Failed to prepare database: ImplementationError: Failed to load helper `utils` into a Callable!  Sorry, could not interpret "utils" because its underlying implementation has a problem:
------------------------------------------------------
• Missing the `fn` property.
------------------------------------------------------

If you are the maintainer of "utils", then you can change its implementation to solve the problem above.  Otherwise, please file a bug report with the maintainer, or fork your own copy and fix that.
 [?] See https://sailsjs.com/support for help.
    at flaverr (/opt/konga/node_modules/flaverr/index.js:94:15)
    at helpBuildMachine (/opt/konga/node_modules/machine/lib/private/help-build-machine.js:178:11)
    at Function.buildWithCustomUsage (/opt/konga/node_modules/machine/lib/build-with-custom-usage.js:38:10)
    at Hook.furnishHelper (/opt/konga/node_modules/sails/lib/hooks/helpers/index.js:411:68)
    at Hook.wrapper [as furnishHelper] (/opt/konga/node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at /opt/konga/node_modules/sails/lib/hooks/helpers/private/load-helpers.js:94:31
    at /opt/konga/node_modules/@sailshq/lodash/lib/index.js:3228:15
    at baseForOwn (/opt/konga/node_modules/@sailshq/lodash/lib/index.js:2199:14)
    at /opt/konga/node_modules/@sailshq/lodash/lib/index.js:3198:18
    at Function.<anonymous> (/opt/konga/node_modules/@sailshq/lodash/lib/index.js:3501:13)
    at /opt/konga/node_modules/sails/lib/hooks/helpers/private/load-helpers.js:42:9
    at helpBuildDictionary (/opt/konga/node_modules/include-all/lib/help-build-dictionary.js:135:10)
    at Function.module.exports.optional (/opt/konga/node_modules/include-all/index.js:67:10)
    at loadHelpers (/opt/konga/node_modules/sails/lib/hooks/helpers/private/load-helpers.js:24:14)
    at Hook.initialize (/opt/konga/node_modules/sails/lib/hooks/helpers/index.js:285:7)
    at Hook.wrapper [as initialize] (/opt/konga/node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at /opt/konga/node_modules/sails/lib/hooks/index.js:122:20
    at /opt/konga/node_modules/sails/node_modules/async/dist/async.js:421:16
    at processQueue (/opt/konga/node_modules/sails/node_modules/async/dist/async.js:1565:20)
    at taskComplete (/opt/konga/node_modules/sails/node_modules/async/dist/async.js:1588:9)
    at /opt/konga/node_modules/sails/node_modules/async/dist/async.js:1612:17
    at /opt/konga/node_modules/sails/node_modules/async/dist/async.js:906:16

**Comment by rpt02** [comment]
I have the same problem. When I try to install Konga donwloaded from github, I get the same error messages.
