### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by AdityaAnand1** [pantsel/konga#641]
176 open issues and no commits since a few months 😅 

Does this still work? Are there any good alternatives?

**Comment by dsteinkopf** [comment]
see #621 
Konga seems dead :-(   I haven't found any good alternatives. Does anyone else have one?

**Comment by OneideLuizSchneider** [comment]
I'm using it with version 2.1.4 of kong and works well.
I didn't test with the 2.2.0.

**Comment by agostlg** [comment]
Can't install, I used gojira.

npm ERR! Linux 5.4.0-54-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/luiz-agostinho/konga/npm-debug.log

**Comment by mloskot** [comment]
@OneideLuizSchneider What database backend are you using? See https://github.com/pantsel/konga/issues/645

**Comment by OneideLuizSchneider** [comment]
Hi @mloskot 
For Postgres, you need to use version 9.6(I tried v12 but didn't work), and MongoDB you can use 4.0 or superior.
I'm using both, in different projects.

**Comment by mloskot** [comment]
@OneideLuizSchneider I am using 9.6 precisely. Are you using TLS and do you require TLS for Konga - PostgreSQL connections? Which version of TLS?

**Comment by OneideLuizSchneider** [comment]
No, it's just in the same VPC on GCP.

**Comment by mloskot** [comment]
@OneideLuizSchneider Well, that what may be making the difference then: with the SSL the server dies, without the SSL all working fine. Thanks for the confirmation!

**Comment by devudopw** [comment]
> see #621
> Konga seems dead :-( I haven't found any good alternatives. Does anyone else have one?

https://github.com/pocketdigi/kong-admin-ui
Using kong-admin-ui with kong 2.1.3 now, no problem yet

**Comment by nikirago** [comment]
https://github.com/yesinteractive/kong-map for declarative management of Kong.
