### ISSUE TITLE
 Error: Invalid `hookTimeout` config.

### ISSUE THREAD

**Issue by qianyugang** [pantsel/konga#674]
When I run konga with "npm run production" , It gives the following error：

```
error: Failed to lift app: Error: Invalid `hookTimeout` config!  If set, this should be a positive whole number, but instead got `120000`.  Please change this setting, then try lifting again.
    at loadHook (/root/konga/node_modules/sails/lib/app/private/loadHooks.js:172:21)
    at userhooks (/root/konga/node_modules/sails/lib/app/private/loadHooks.js:291:11)
    at /root/konga/node_modules/sails/node_modules/async/dist/async.js:3853:24
    at replenish (/root/konga/node_modules/sails/node_modules/async/dist/async.js:946:17)
    at iterateeCallback (/root/konga/node_modules/sails/node_modules/async/dist/async.js:931:17)
    at /root/konga/node_modules/sails/node_modules/async/dist/async.js:906:16
    at /root/konga/node_modules/sails/node_modules/async/dist/async.js:3858:13
    at /root/konga/node_modules/sails/lib/app/private/loadHooks.js:241:38
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

.env file  is as follows
```
PORT=1337
NODE_ENV=production
KONGA_HOOK_TIMEOUT=120000
DB_ADAPTER=postgres
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=xxx
DB_USER=xxx
DB_PASSWORD=xxx
KONGA_LOG_LEVEL=warn
```

- kong version:2.1.3
- npm -v:6.14.6
- node -v:10.22.1

How to fix it?

**Comment by fardhana** [comment]
I am experiencing the same issue in `node -v : v14.16.0`

**Comment by ntgiangictu** [comment]
I've met this case and cannot solve. Anyone can help me?
# node -v
v12.22.1

# kong version
2.4.1

# npm -v
7.14.0

**Comment by fardhana** [comment]
Hi @ntgiangictu since, database config is optional. i end up run konga without database configuration 
```
PORT=1337
NODE_ENV=development
KONGA_HOOK_TIMEOUT=120000
KONGA_LOG_LEVEL=debug
TOKEN_SECRET=some_secret_token
```
Run with this config solve my issue.

**Comment by ntgiangictu** [comment]
> Hi @ntgiangictu since, database config is optional. i end up run konga without database configuration
> 
> ```
> PORT=1337
> NODE_ENV=development
> KONGA_HOOK_TIMEOUT=120000
> KONGA_LOG_LEVEL=debug
> TOKEN_SECRET=some_secret_token
> ```
> 
> Run with this config solve my issue.

Hi @fardhana 
I try to change .env as you talked, however, it seems error when install sails.
Can you explain more details about this?

**Comment by ntgiangictu** [comment]
I try to fresh install Konga in CentOS 7. However, $ npm install still return errors.
It seem npm packages too olds or something like that.
Finally, when I started, it still return error hookTimeout although I don't use database.
