### ISSUE TITLE
Randomly "Lowering Sails"

### ISSUE THREAD

**Issue by JeremyCanfield** [pantsel/konga#726]
About once or twice a week, our Konga container on Docker will shut down. I've set KONGA_LOG_LEVEL=silly. Prior to the Konga container shut down, I see normal events like this.

`Disabling CSRF protection for / since request has no session.`
`View override argument passed to res.view():  homepage`
`Serving view at rel path:  homepage`
`View root:  /app/views`
`Rendering view: "homepage" (located @ "/app/views/homepage")`
`• using configured layout:: layout (located @ "/app/views/layout")`

When the Konga container shuts down, I see events like this.

`Lowering sails...`
`Sent kill signal to child process (19)...`
`      throw er; // Unhandled 'error' event`
`events.js:174`
`    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)`
`Error: read ECONNRESET`
`Emitted 'error' event at:`
`    at emitErrorNT (internal/streams/destroy.js:91:8)`
`    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)`
`    at process._tickCallback (internal/process/next_tick.js:63:19)`

I am not sure how to interpret these events to ultimately determine why the Konga container randomly shuts down, nor I am sure what can be done to fix whatever issue is causing the container to randomly shut down.

**Comment by DeclanPaulKeane** [comment]
Hey @JeremyCanfield , this might be useful: https://konghq.com/blog/kong-gateway-enterprise-2-3-now-generally-available/. "....and notably the inclusion of a user interface, Kong Manager". So you can use the Kong built tool for free :)
