### ISSUE TITLE
Migration using postgres

### ISSUE THREAD

**Issue by vincentmarkcelino** [pantsel/konga#747]
Hello guys, im having problem executing this command: node ./bin/konga.js  prepare --adapter postgres --uri postgresql://localhost:5432/konga

Postgres: 14

It gives me this error:
Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 }
    at Connection.parseR (/root/konga/node_modules/pg/lib/connection.js:426:9)
    at Connection.parseMessage (/root/konga/node_modules/pg/lib/connection.js:345:17)
    at Socket.<anonymous> (/root/konga/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:126:14)

**Comment by fertab** [comment]
Any update of this? I'm facing the same issue

**Comment by hellovigoss** [comment]
same issue, I think pgsql's version made it

**Comment by hellovigoss** [comment]
degrade postgresql@11.17.x made konga worked   @fertab

**Comment by diegonc** [comment]
This is because SCRAM-SHA-256 passwords in Postgres 14.

`pg` needs to be updated to a version which has [this](https://github.com/brianc/node-postgres/commit/5a92ba3701e576b91697e653c6c369500811e9e5) commit (it seems to be at least v7.14.0).

I'm not sure how to do it, though, as it is used through sailsjs. Just upgrading `sails-postgresql` to the latest version won't work as it throws:

```
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

Cannot initialize Waterline.

The installed version of adapter `sails-postgresql` is too new!

Please try installing a version < 1.0.

-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
```

and version `< 1.0` seems to be stucked at `pg@4.x.x`

**Comment by pravynandas** [comment]
For me the issue came with command `npm start` which the default .env_example was copied as .env and used. After removing .env the command worked fine. I guess konga runs just fine without postgresql backend (considering the complexity involved in this issue to be resolved).

**Comment by tiandong19860806** [comment]
@pravynandas ,
 
I also had the same issue at startup konga.

1. error info
Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 }
    at Connection.parseR (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:426:9)
    at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:345:17)
    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

2.  enviroment , 
OS : CentOS 7.9 X64
docker : Docker version 20.10.17, build 100c701
konga : pantsel/konga:latest
PG : PG-14 x64

3. yml file:
![image](https://user-images.githubusercontent.com/12596666/201825239-17ec13fa-8822-4b22-9647-d9d22a3bf62a.png)

4. postgres connect is OK at client
![image](https://user-images.githubusercontent.com/12596666/201825400-0123b138-b1ba-4122-8bde-12a99aa33073.png)

**Comment by phyokyawdev** [comment]
> This is because SCRAM-SHA-256 passwords in Postgres 14.
> 
> `pg` needs to be updated to a version which has [this](https://github.com/brianc/node-postgres/commit/5a92ba3701e576b91697e653c6c369500811e9e5) commit (it seems to be at least v7.14.0).


Thanks for the information, I am facing the same issue with `sails-postgresql` and `postgresql-14`. 

Solved by downgrading to postgresql version which support md5 as default.
