### ISSUE TITLE
Hey Rafael, try setting KONGA_HOOK_TIMEOUT env var to 120000. Check out the FAQ section of the README.md

### ISSUE THREAD

**Issue by anigkus** [pantsel/konga#775]
Hey Rafael, try setting KONGA_HOOK_TIMEOUT env var to 120000. Check out the FAQ section of the README.md

_Originally posted by @pantsel in https://github.com/pantsel/konga/issues/284#issuecomment-425714143_

I'm setting `KONGA_HOOK_TIMEOUT`,has error:

```
# ls -al | grep .env
-rw-r--r--.   1 root root    225 May 27 01:21 .env
-rw-r--r--.   1 root root    225 May 26 14:31 .env_example
# cat .env
PORT=1337
NODE_ENV=production
KONGA_HOOK_TIMEOUT=120000
DB_ADAPTER=postgres
DB_URI=postgresql://localhost:5432/konga
DB_USER=konga
DB_PASSWORD=konga123456
DB_DATABASE=konga
KONGA_LOG_LEVEL=warn
TOKEN_SECRET=some_secret_token
```

```
# node ./bin/konga.js  prepare --adapter postgres --uri postgresql://localhost:5432/konga
Preparing database...
(node:475025) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
error: Failed to prepare database: Error: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 60000)
    at Timeout.tooLong [as _onTimeout] (/root/konga/node_modules/sails/lib/app/private/loadHooks.js:85:21)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

# postgresql  DB is ok.
```
# telnet localhost 5432
Trying ::1...
Connected to localhost.
Escape character is '^]'.
^CConnection closed by foreign host.
```

**Comment by vichaos** [comment]
Duplicate to #646, it can be solved by this [PR](https://github.com/pantsel/konga/pull/740).
