### ISSUE TITLE
Konga unable to start on fresh installation using packer and terraform

### ISSUE THREAD

**Issue by ahsandar** [pantsel/konga#87]
re-Installed `Konga`using `packer` and `terraform` and getting following error , unable to start it 

```
> kongadmin@0.8.2 production /opt/apps/konga
> node --harmony app.js --prod

error: `include-all` attempted to `require(/opt/apps/konga/api/hooks/api-health-checks.js)`, but an error occurred::
Details:SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/apps/konga/api/events/api-health-checks.js:17:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/apps/konga/api/hooks/api-health-checks.js:3:25)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /opt/apps/konga/node_modules/include-all/lib/help-include-all-sync.js:271:33
    at Array.forEach (native)
    at _recursivelyIncludeAll (/opt/apps/konga/node_modules/include-all/lib/help-include-all-sync.js:174:11)
    at includeAll (/opt/apps/konga/node_modules/include-all/lib/help-include-all-sync.js:292:5)
    at helpBuildDictionary (/opt/apps/konga/node_modules/include-all/lib/help-build-dictionary.js:43:15)
    at Function.module.exports.optional (/opt/apps/konga/node_modules/include-all/index.js:67:10)
    at Array.async.auto.hooksFolder (/opt/apps/konga/node_modules/sails/lib/hooks/moduleloader/index.js:474:22)```

**Comment by pantsel** [comment]
Hello, @ahsandar ,

I'm not familiar with either <code>packer</code> nor <code>terraform</code> so I don't know if they have any requirements that Konga doesn't meet.

For example, there is no syntax error in <code>api/hooks/api-health-checks.js</code> as far as I can see. 

Maybe the project did not build correctly?

I would suggest using the docker image tho, as it is fully tested and working.

**Comment by ahsandar** [comment]
trying to run `npm install` in the directory returns following 
`npm WARN lifecycle kongadmin@0.8.2~postinstall: cannot run in wd %s %s (wd=%s) kongadmin@0.8.2 bower --allow-root install /opt/apps/konga`

**Comment by ahsandar** [comment]
just doing following 
`npm install -g bower gulp sails sails-postgresql`
`checkout konga`
`npm install`
`/usr/local/bin/bower install --allow-root`

**Comment by ahsandar** [comment]
Updated node from `4.6.2`  to `6.11.2`
Fixed the issue, not sure how it managed to work before

**Comment by pantsel** [comment]
Great man! Thanks for the feedback and the solution. That way someone else that stumbles across the same issue can use it as reference.

Cheers!
